Braille_Text_Up::
	.braille "HAUT$"

Braille_Text_Down::
	.braille "BAS$"

Braille_Text_Right::
	.braille "DROITE$"

Braille_Text_Left::
	.braille "GAUCHE$"

Braille_Text_Cut::
	.braille "COUPE$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille "*$"

Braille_Text_Comma::
	.braille ",$"

Braille_Text_Everything::
	.braille "TOUT$"

Braille_Text_HasMeaning1::
	.braille "A UN SENS$"

Braille_Text_Existence::
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2::
	.braille "A UN SENS$"

Braille_Text_BeingAlive::
	.braille "ETRE VIVANT$"

Braille_Text_HasMeaning3::
	.braille "A UN SENS$"

Braille_Text_HaveDreams::
	.braille "CROIS EN TOI$"

Braille_Text_UsePower::
	.braille "BATS TOI*$"

Braille_Text_LetTheTwo::
	.braille "LAISSE LES$"

Braille_Text_Glittering::
	.braille "DEUX PIERRES$"

Braille_Text_Stones::
	.braille "BRILLANTES$"

Braille_Text_OneInRed::
	.braille "UNE EN ROUGE$"

Braille_Text_OneInBlue::
	.braille "UNE EN BLEU$"

Braille_Text_ConnectThe::
	.braille "CONNECTER LE$"

Braille_Text_Past::
	.braille "PASSE*$"

Braille_Text_TwoFriends::
	.braille "PARTAGER LA$"

Braille_Text_Sharing::
	.braille "FORCE A DEUX$"

Braille_Text_PowerOpen::
	.braille "AMIS OUVRE$"

Braille_Text_AWindowTo::
	.braille "LA PORTE$"

Braille_Text_ANewWorld::
	.braille "D UN MONDE$"

Braille_Text_ThatGlows::
	.braille "NOUVEAU*$"

Braille_Text_TheNext::
	.braille "LE MONDE$"

Braille_Text_WorldWaits::
	.braille "SUIVANT$"

Braille_Text_ForYou::
	.braille "T ATTEND*$"
