@ Unused
Text_WelcomeTradeCenter::
	.string "Bienvenue au CENTRE TROC\n"
	.string "du CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeColosseum::
	.string "Bienvenue au COLISEE du\n"
	.string "CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule::
	.string "Bienvenue au BLOC TEMPOREL\n"
	.string "du CLUB LINK POKéMON.$"

Text_PleaseComeAgain::
	.string "A la prochaine!$"

@ Unused
Text_HavingDiscountSaleToday::
	.string "Bienvenue!\p"
	.string "Nous avons une promotion\n"
	.string "aujourd'hui!$"

@ Unused
Text_PlayerWhatCanIDoForYou::
	.string "Bienvenue {PLAYER}{KUN}!\p"
	.string "Que puis-je faire pour vous?$"
