Help_Text_WhatShouldIDo::
	.string "Que faire dans ce cas?$"

Help_Text_HowDoIDoThis::
	.string "Comment faire ça?$"

Help_Text_WhatDoesThisTermMean::
	.string "Que signifie ce terme?$"

Help_Text_AboutThisGame::
	.string "A propos de ce jeu$"

Help_Text_TypeMatchupList::
	.string "Liste des rapports entre les types$"

Help_Text_Exit::
	.string "SORTIR$"

Help_Text_Cancel::
	.string "RETOUR$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Pour obtenir des indices sur\n"
	.string "des situations complexes.$"

Help_Text_DescHowDoIDoThis::
	.string "Des instructions détaillées sur\n"
	.string "diverses opérations.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Des explications détaillées sur\n"
	.string "des noms apparaissant dans le jeu.$"

Help_Text_DescAboutThisGame::
	.string "Des explications détaillées sur\n"
	.string "le jeu.$"

Help_Text_DescTypeMatchupList::
	.string "Les rapports entre les POKéMON\n"
	.string "et les capacités sont classés.$"

Help_Text_DescExit::
	.string "Pour quitter le menu d'aide.$"

Help_Text_Greetings::
	.string "Bienvenue! Tu es dans le système\n"
	.string "d'AIDE. Appelle-moi dès que tu en\l"
	.string "as besoin en appuyant sur le bouton\l"
	.string "L ou R. Les messages d'aide changent\l"
	.string "en fonction de la situation, alors\l"
	.string "n'hésite pas à les consulter.$"

Help_Text_PlayingForFirstTime::
	.string "Je joue pour la première fois.$"

Help_Text_WhatShouldIBeDoing::
	.string "Que dois-je faire?$"

Help_Text_CantGetOutOfRoom::
	.string "Je ne peux pas sortir!$"

Help_Text_CantFindPersonIWant::
	.string "Je ne trouve pas quelqu'un.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "J'ai déjà parlé à tout le monde.$"

Help_Text_SomeoneBlockingMyWay::
	.string "Quelqu'un bloque le passage.$"

Help_Text_ICantGoOn::
	.string "Je ne peux pas continuer.$"

Help_Text_OutOfThingsToDo::
	.string "Je ne sais plus quoi faire.$"

Help_Text_WhatHappenedToItemIGot::
	.string "Où sont rangés les objets?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Que faire dans cette aventure?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Différences entre routes et forêts.$"

Help_Text_HowAreCavesDifferent::
	.string "Particularités des grottes.$"

Help_Text_HowDoIProgress::
	.string "Comment progresser?$"

Help_Text_WhenCanIUseItem::
	.string "Quand utiliser les objets?$"

Help_Text_WhatsABattle::
	.string "Qu'est-ce qu'un combat?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Comment préparer un combat?$"

Help_Text_WhatIsAMonsVitality::
	.string "A quoi servent les PV?$"

Help_Text_MyMonsAreHurt::
	.string "Mes POKéMON sont blessés.$"

Help_Text_WhatIsStatusProblem::
	.string "Qu'est-ce qu'un problème de statut?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Et si tous mes POKéMON sont KO?$"

Help_Text_CantCatchMons::
	.string "Impossible d'attraper un POKéMON!$"

Help_Text_RanOutOfPotions::
	.string "Je n'ai plus de POTION.$"

Help_Text_CanIBuyPokeBalls::
	.string "Puis-je acheter des POKé BALLS?$"

Help_Text_WhatsATrainer::
	.string "Qu'est-ce qu'un DRESSEUR?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "Comment vaincre un DRESSEUR?$"

Help_Text_WhereDoMonsAppear::
	.string "Où apparaissent les POKéMON?$"

Help_Text_WhatAreMoves::
	.string "Les capacités des POKéMON.$"

Help_Text_WhatAreHiddenMoves::
	.string "Les capacités SECRETES.$"

Help_Text_WhatMovesShouldIUse::
	.string "Quelles capacités utiliser?$"

Help_Text_WantToAddMoreMoves::
	.string "Je veux plus de capacités.$"

Help_Text_WantToMakeMonStronger::
	.string "Rendre mes POKéMON plus forts.$"

Help_Text_FoeMonsTooStrong::
	.string "L'ennemi est trop fort!$"

Help_Text_WhatDoIDoInCave::
	.string "Que faire dans les grottes?$"

Help_Text_NothingIWantToKnow::
	.string "Je ne veux rien savoir!$"

Help_Text_WhatsPokemonCenter::
	.string "Qu'est-ce qu'un CENTRE POKéMON?$"

Help_Text_WhatsPokemonMart::
	.string "Qu'est-ce qu'une BOUTIQUE POKéMON?$"

Help_Text_WantToEndGame::
	.string "Je veux arrêter de jouer.$"

Help_Text_WhatsAMon::
	.string "Qu'est-ce qu'un POKéMON?$"

Help_Text_WhatIsThatPersonLike::
	.string "Comment est cette personne?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "A quoi sert une capacité SECRETE?$"

Help_Text_WhatDoIDoInSafari::
	.string "Que faire dans le JEU SAFARI?$"

Help_Text_WhatAreSafariRules::
	.string "Les règles du JEU SAFARI.$"

Help_Text_WantToEndSafari::
	.string "Terminer un JEU SAFARI.$"

Help_Text_WhatIsAGym::
	.string "Qu'est-ce qu'une ARENE?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "Tu incarnes le personnage principal\n"
	.string "du jeu parti explorer le monde des\l"
	.string "POKéMON. En parlant aux gens\l"
	.string "et en résolvant des énigmes, tu\l"
	.string "ouvriras de nouvelles voies. Tu\l"
	.string "pourras compter sur tes POKéMON\l"
	.string "pour finir ta quête.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "Quand tu rencontres quelqu'un,\n"
	.string "approche-toi de cette personne et\l"
	.string "appuie sur le bouton A pour\l"
	.string "commencer une discussion. De la\l"
	.string "même façon, tu peux aussi examiner\l"
	.string "des objets. Utilise souvent ce bouton\l"
	.string "pour obtenir plein d'informations.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "Des tapis rouges se trouvent près\n"
	.string "des marches ou des sorties de\l"
	.string "bâtiments. Place-toi dessus et appuie\l"
	.string "sur la manette {PLUS} vers les marches\l"
	.string "ou la sortie pour continuer.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "Ce n'est pas vraiment un problème.\n"
	.string "Parle aux gens, lis les panneaux et\l"
	.string "fouille un peu partout. Parfois, il\l"
	.string "suffit simplement d'aller dans une\l"
	.string "nouvelle ville ou un nouvel endroit.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Essaie d'atteindre une nouvelle route\n"
	.string "ou un nouvel endroit.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "La cause se trouve peut-être en\n"
	.string "ville ou dans un bâtiment. Essaie\l"
	.string "encore de parler aux gens du coin.\l"
	.string "Tu pourras les aider s'ils ont un\l"
	.string "problème à résoudre. Après ça,\l"
	.string "parle de nouveau à la personne\l"
	.string "bloquant ton chemin.$"

Help_Text_AnswerICantGoOn::
	.string "Essaie de parler aux gens en allant\n"
	.string "vers eux et en appuyant sur le\l"
	.string "bouton A. Examine aussi les arbres\l"
	.string "et les pierres étranges avec le même\l"
	.string "bouton. De même, avec la manette {PLUS},\l"
	.string "essaie d'atteindre des endroits qui\l"
	.string "semblent inaccessibles.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Essaie d'aller à des endroits que\n"
	.string "tu n'as pas encore visités.\l"
	.string "Examine aussi tout ce qui te semble\l"
	.string "étrange avec le bouton A.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Tous les objets que tu reçois vont\n"
	.string "directement dans ton SAC. Ils sont\l"
	.string "automatiquement classés dans une\l"
	.string "des trois poches. Consulte la section\l"
	.string "“Comment faire ça?” dans le\l"
	.string "système d'AIDE pour plus d'infos sur\l"
	.string "l'utilisation du SAC.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "Si tes POKéMON sont blessés au\n"
	.string "combat, amène-les dans un CENTRE\l"
	.string "POKéMON pour les faire soigner.\l"
	.string "Profites-en pour sauvegarder ta\l"
	.string "partie. N'oublie pas de prendre des\l"
	.string "objets de soin avant de faire un\l"
	.string "grand voyage.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Les forêts, contrairement aux routes,\n"
	.string "peuvent parfois ressembler à de vrais\l"
	.string "labyrinthes. Toutes les forêts ont\l"
	.string "une sortie, alors n'abandonne pas\l"
	.string "si tu te perds.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Les grottes sont sombres et\n"
	.string "dangereuses. Des POKéMON sauvages\l"
	.string "peuvent en surgir n'importe quand. Si\l"
	.string "tu as besoin, cours vers un CENTRE\l"
	.string "POKéMON ou utilise des objets. Des\l"
	.string "villes nouvelles t'attendent de\l"
	.string "l'autre côté, alors fonce!$"

Help_Text_AnswerHowDoIProgress::
	.string "Le but du jeu est de dresser tes\n"
	.string "POKéMON et de progresser. Il te\l"
	.string "faudra réunir des infos et résoudre\l"
	.string "des problèmes. Par exemple, que\l"
	.string "faire pour contourner un obstacle,\l"
	.string "ou comment faire bouger quelqu'un \l"
	.string "de ton chemin.$"

Help_Text_AnswerWhenCanIUseItem::
	.string "Il y a plusieurs types d'objets.\n"
	.string "Certains ne peuvent être utilisés\l"
	.string "que sur le terrain, d'autres ne\l"
	.string "servent que dans les combats, alors\l"
	.string "que d'autres peuvent être utilisés\l"
	.string "n'importe quand. Tu seras alerté\l"
	.string "si un objet ne peut pas être utilisé.$"

Help_Text_AnswerWhatsABattle::
	.string "En combat, les POKéMON tentent de\n"
	.string "réduire l'énergie de leurs adversaires\l"
	.string "exprimée en PV. Un POKéMON avec\l"
	.string "zéro PV perd un combat. En gagnant,\l"
	.string "ils gagnent des points d'EXP. qui les\l"
	.string "font changer de niveau (devenir plus\l"
	.string "forts).$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "Tout d'abord, soigne tous les\n"
	.string "POKéMON de ton équipe dans\l"
	.string "un CENTRE POKéMON. Tu peux\l"
	.string "aussi acheter des objets de soin dans\l"
	.string "les BOUTIQUES POKéMON.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "L'énergie d'un POKéMON est exprimée\n"
	.string "en PV. A chaque blessure, des PV\l"
	.string "sont soustraits. Le POKéMON est KO\l"
	.string "s'il atteint zéro PV. Soigne les\l"
	.string "POKéMON blessés dans un CENTRE\l"
	.string "POKéMON ou avec des objets de soin.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "Les POKéMON peuvent se reposer\n"
	.string "dans les CENTRES POKéMON. Leurs\l"
	.string "problèmes de statut seront résolus et\l"
	.string "leurs PV restaurés avec une machine\l"
	.string "spéciale. C'est un service gratuit,\l"
	.string "n'hésite pas à l'utiliser.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "Les problèmes de statut (brûlure,\n"
	.string "paralysie, poison, sommeil et gel)\l"
	.string "sont créés par les attaques de tes\l"
	.string "adversaires. Ils peuvent être soignés\l"
	.string "dans un CENTRE POKéMON ou avec\l"
	.string "des objets de soin.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "Si tous les POKéMON de ton\n"
	.string "équipe (ceux avec toi) sont KO, tu\l"
	.string "perds de l'argent et retournes à la\l"
	.string "maison ou dans un CENTRE POKéMON.\l"
	.string "Pour limiter ce risque, prends\l"
	.string "l'habitude d'aller souvent dans un\l"
	.string "CENTRE POKéMON.$"

Help_Text_AnswerCantCatchMons::
	.string "Les POKéMON encore vigoureux\n"
	.string "s'échappent plus facilement des\l"
	.string "POKé BALLS. Essaie de réduire leurs\l"
	.string "PV ou de changer leur statut avant\l"
	.string "de les attraper. Le POKéMON est\l"
	.string "sur le point de se faire prendre si\l"
	.string "la POKé BALL reste longtemps fermée.$"

Help_Text_AnswerRanOutOfPotions::
	.string "Les objets peuvent être achetés\n"
	.string "dans des magasins appelés \l"
	.string "BOUTIQUES POKéMON qui ne\l"
	.string "se trouvent qu'en milieu urbain.\l"
	.string "N'oublie pas d'y faire un tour pour\l"
	.string "acheter les objets nécessaires à\l"
	.string "ton voyage.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "Tu peux acheter des POKé BALLS\n"
	.string "dans la BOUTIQUE POKéMON de chaque\l"
	.string "ville. N'oublie pas d'y faire un tour\l"
	.string "pour acheter des objets nécessaires\l"
	.string "à ton voyage.$"

Help_Text_AnswerWhatsATrainer::
	.string "Les DRESSEURS sont des personnes\n"
	.string "qui combattent avec leurs POKéMON.\l"
	.string "Tu en rencontreras partout et devras\l"
	.string "les affronter si jamais tu croises\l"
	.string "leur regard. Alors fais attention.$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "Pour battre un DRESSEUR, utilise\n"
	.string "un POKéMON ayant l'avantage du type\l"
	.string "sur les POKéMON adverses. Tu peux\l"
	.string "aussi utiliser des POKéMON de niveau\l"
	.string "bien supérieur ou en plus grand\l"
	.string "nombre pour gagner facilement.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Les POKéMON sauvages apparaissent\n"
	.string "dans les hautes herbes des forêts et\l"
	.string "au bord des routes. Dans les\l"
	.string "grottes, ils surgissent de n'importe\l"
	.string "où. Il n'y a pas de POKéMON sauvages\l"
	.string "dans les villes, tu y seras à l'abri.$"

Help_Text_AnswerWhatAreMoves::
	.string "Les POKéMON peuvent apprendre\n"
	.string "jusqu'à quatre techniques, ou\l"
	.string "capacités. Certaines servent\l"
	.string "seulement à attaquer et d'autres ont\l"
	.string "des effets spéciaux. Les types de\l"
	.string "capacités qui peuvent être apprises\l"
	.string "dépendent du POKéMON.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "Les capacités SECRETES sont\n"
	.string "indispensables pour progresser \l"
	.string "dans le jeu. Pour les utiliser hors\l"
	.string "d'un combat, même avec un POKéMON\l"
	.string "KO, ouvre le menu “POKéMON” et\l"
	.string "choisis le POKéMON connaissant\l"
	.string "la capacité désirée.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Sélectionne ATTAQUE pour ouvrir le\n"
	.string "menu des capacités. Pense bien aux\l"
	.string "types pour choisir la capacité la\l"
	.string "plus efficace. Tu peux voir leurs\l"
	.string "effets en ouvrant CAP. CONNUES\l"
	.string "dans le RESUME d'un POKéMON.$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "Les POKéMON ne peuvent pas\n"
	.string "apprendre plus de quatre capacités.\l"
	.string "Elles peuvent s'apprendre quand le\l"
	.string "POKéMON monte de niveau mais\l"
	.string "aussi avec des CT (CAPSULES\l"
	.string "TECHNIQUES), des CS (CAPSULES\l"
	.string "SECRETES) ou avec des gens.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "La clé pour dresser tes POKéMON\n"
	.string "est de les faire remporter beaucoup\l"
	.string "de combats. Accumule les points EXP.\l"
	.string "en gagnant pour faire monter de\l"
	.string "niveau les POKéMON ayant combattu.\l"
	.string "Affronte souvent des POKéMON\l"
	.string "sauvages pour renforcer ton équipe.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "Si tes adversaires sont trop forts,\n"
	.string "essaie de monter un peu le niveau de\l"
	.string "tes POKéMON en rebroussant chemin\l"
	.string "et en affrontant des POKéMON\l"
	.string "sauvages. Tu peux aussi affronter des\l"
	.string "DRESSEURS que tu n'avais pas\l"
	.string "encore rencontrés.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Dans les grottes, contrairement aux\n"
	.string "routes et aux forêts, les POKéMON\l"
	.string "peuvent surgir de n'importe où.\l"
	.string "Soigne vite les POKéMON blessés\l"
	.string "dans un CENTRE POKéMON ou avec\l"
	.string "des objets de soin pour ne pas\l"
	.string "prendre de risques inutiles.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Aie confiance en tes connaissances\n"
	.string "et dans la force de tes POKéMON.\l"
	.string "Crois en toi pour trouver ton chemin.$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "Un CENTRE POKéMON se reconnaît à\n"
	.string "son toit rouge et à son logo. Chaque\l"
	.string "centre permet de soigner tes POKéMON\l"
	.string "et d'utiliser les PC pour préparer\l"
	.string "tes voyages. Au premier étage, des\l"
	.string "équipements te permettent de te\l"
	.string "connecter avec tes amis.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "Une BOUTIQUE POKéMON se\n"
	.string "reconnaît à son toit bleu et à son\l"
	.string "logo. Tu peux acheter ou vendre des\l"
	.string "objets dans toutes les boutiques,\l"
	.string "mais selon la ville, elles peuvent\l"
	.string "proposer des articles différents.$"

Help_Text_AnswerWantToEndGame::
	.string "Tu peux sauvegarder ta partie\n"
	.string "en choisissant SAUVER dans le menu.\l"
	.string "Tu peux éteindre ta console une fois\l"
	.string "ta partie sauvegardée. En rallumant\l"
	.string "ta console, tu reprends ta partie là\l"
	.string "où tu l'avais laissée.$"

Help_Text_AnswerWhatsAMon::
	.string "Les POKéMON sont des créatures\n"
	.string "entourées de mystère. On peut les\l"
	.string "voir dans les herbes, la mer ou les \l"
	.string "grottes. Ils obéissent au DRESSEUR\l"
	.string "qui les a attrapés.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Utilise le MEMORYDEX dans la\n"
	.string "poche OBJ. RARES de ton SAC.\l"
	.string "Il peut te donner des indices, ne\l"
	.string "l'oublie pas.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "Une capacité SECRETE est enseignée\n"
	.string "à un POKéMON grâce à une CS\l"
	.string "(CAPSULE SECRETE). Elles sont\l"
	.string "essentielles pour continuer ton\l"
	.string "aventure, en te permettant d'éclairer\l"
	.string "les grottes, de couper des arbres ou\l"
	.string "de voyager sur l'eau par exemple.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Essaie d'attraper des POKéMON\n"
	.string "sauvages en lançant des SAFARI\l"
	.string "BALLS. Tu peux conserver tous\l"
	.string "les objets que tu trouves pendant\l"
	.string "le jeu.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "Le JEU SAFARI se termine dès que tu\n"
	.string "as parcouru une certaine distance ou\l"
	.string "lancé toutes tes SAFARI BALLS. Ouvre\l"
	.string "le menu pour voir le nombre de pas\l"
	.string "et de SAFARI BALLS restant.$"

Help_Text_AnswerWantToEndSafari::
	.string "Pour terminer le JEU SAFARI, ouvre\n"
	.string "le menu et choisis “PARTIR” dans\l"
	.string "la liste.$"

Help_Text_AnswerWhatIsAGym::
	.string "Les ARENES POKéMON sont\n"
	.string "contrôlées par la LIGUE POKéMON\l"
	.string "et permettent aux DRESSEURS de\l"
	.string "s'entraîner. On les trouve dans les\l"
	.string "villes et elles sont représentées par\l"
	.string "un CHAMPION. Bats ce CHAMPION\l"
	.string "pour gagner le BADGE de l'ARENE.$"

Help_Text_UsingPokedex::
	.string "Utiliser le POKéDEX$"

Help_Text_UsingPokemon::
	.string "Utiliser un POKéMON$"

Help_Text_UsingSummary::
	.string "Utiliser le RESUME$"

Help_Text_UsingSwitch::
	.string "Utiliser l'ORDRE$"

Help_Text_UsingItem::
	.string "Utiliser un OBJET$"

Help_Text_UsingBag::
	.string "Utiliser le SAC$"

Help_Text_UsingAnItem::
	.string "Utiliser un objet du SAC$"

Help_Text_UsingKeyItem::
	.string "Utiliser un objet rare$"

Help_Text_UsingPokeBall::
	.string "Utiliser une POKé BALL$"

Help_Text_UsingPlayer::
	.string "Utiliser {PLAYER}$"

Help_Text_UsingSave::
	.string "Utiliser la commande SAUVER$"

Help_Text_UsingOption::
	.string "Utiliser les OPTIONS$"

Help_Text_UsingPotion::
	.string "Utiliser une POTION$"

Help_Text_UsingTownMap::
	.string "Utiliser la CARTE$"

Help_Text_UsingTM::
	.string "Utiliser une CT$"

Help_Text_UsingHM::
	.string "Utiliser une CS$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Utiliser une capacité hors combat$"

Help_Text_RidingBicycle::
	.string "Faire de la BICYCLETTE$"

Help_Text_EnteringName::
	.string "Entrer un nom$"

Help_Text_UsingPC::
	.string "Utiliser un PC$"

Help_Text_UsingBillsPC::
	.string "Utiliser le PC DE {STR_VAR_1}$"

Help_Text_UsingWithdraw::
	.string "Utiliser RETIRER POKéMON$"

Help_Text_UsingDeposit::
	.string "Utiliser DEPOSER POKéMON$"

Help_Text_UsingMove::
	.string "Utiliser DEPLACER POKéMON$"

Help_Text_MovingItems::
	.string "Déplacer les objets$"

Help_Text_UsingPlayersPC::
	.string "Utiliser le PC DE {PLAYER}$"

Help_Text_UsingWithdrawItem::
	.string "Utiliser RETIRER OBJET$"

Help_Text_UsingDepositItem::
	.string "Utiliser DEPOSER OBJET$"

Help_Text_UsingMailbox::
	.string "Utiliser la BOITE LETTR.$"

Help_Text_UsingProfOaksPC::
	.string "Utiliser le PC DU PROF. CHEN$"

Help_Text_OpeningMenu::
	.string "Ouvrir le menu$"

Help_Text_UsingFight::
	.string "Utiliser ATTAQUE$"

Help_Text_UsingPokemon2::
	.string "Utiliser POKéMON$"

Help_Text_UsingShift::
	.string "Utiliser ECHANGER$"

Help_Text_UsingSummary2::
	.string "Utiliser le RESUME$"

Help_Text_UsingBag2::
	.string "Utiliser le SAC$"

Help_Text_ReadingPokedex::
	.string "Lire le POKéDEX$"

Help_Text_UsingHomePC::
	.string "Utiliser le PC à la maison$"

Help_Text_UsingItemStorage::
	.string "Gestion de Stocks d'Objets$"

Help_Text_UsingWithdrawItem2::
	.string "Utiliser RETIRER OBJET$"

Help_Text_UsingDepositItem2::
	.string "Utiliser DEPOSER OBJET$"

Help_Text_UsingMailbox2::
	.string "Utiliser la BOITE LETTR.$"

Help_Text_UsingRun::
	.string "Utiliser la FUITE$"

Help_Text_RegisterKeyItem::
	.string "ENREGISTRER un objet rare$"

Help_Text_UsingBall::
	.string "Utiliser une BALL$"

Help_Text_UsingBait::
	.string "Utiliser un APPAT$"

Help_Text_UsingRock::
	.string "Utiliser une PIERRE$"

Help_Text_UsingHallOfFame::
	.string "Utiliser le PANTHEON$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Sélectionne POKéDEX sur le menu.\n"
	.string "{CIRCLE_2} Choisis un POKéMON avec LISTE,\n"
	.string "HABITATS ou RECHERCHE.\n"
	.string "{CIRCLE_3} Sélectionne un POKéMON pour avoir\n"
	.string "des informations détaillées.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Sélectionne POKéMON sur le menu.\n"
	.string "{CIRCLE_2} Choisis un POKéMON dans ton\n"
	.string "équipe.\n"
	.string "{CIRCLE_3} Sélectionne RESUME, ORDRE\n"
	.string "ou OBJET.$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Sélectionne RESUME.\n"
	.string "{CIRCLE_2} Appuie sur gauche ou droite sur\n"
	.string "la manette {PLUS} pour choisir entre:\n"
	.string "INFOS POKéMON\n"
	.string "APTITUDES\n"
	.string "CAPACITES CONNUES$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Choisis le POKéMON que\n"
	.string "tu veux déplacer.\n"
	.string "{CIRCLE_2} Sélectionne ORDRE.\n"
	.string "{CIRCLE_3} Choisis le POKéMON avec\n"
	.string "lequel tu veux changer de place.\n"
	.string "Le POKéMON à la gauche de\n"
	.string "l'écran part au combat en premier.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Sélectionne OBJET.\n"
	.string "{CIRCLE_2} Sélectionne DONNER pour\n"
	.string "qu'un POKéMON porte un objet, ou\n"
	.string "PRENDR. pour le récupérer.\n"
	.string "Un POKéMON ne peut pas porter\n"
	.string "plus d'un objet!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Sélectionne SAC sur le menu.\n"
	.string "{CIRCLE_2} Appuie sur gauche ou droite sur\n"
	.string "la manette {PLUS} pour choisir entre:\n"
	.string "OBJETS\n"
	.string "OBJ. RARES\n"
	.string "POKé BALLS\n"
	.string "Choisis un objet avec bas ou haut.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Sélectionne la POCHE OBJETS.\n"
	.string "{CIRCLE_2} Choisis un objet avec haut et bas\n"
	.string "sur la manette {PLUS}.\n"
	.string "{CIRCLE_3} Sélectionne UTILIS. pour utiliser\n"
	.string "l'objet sélectionné.\n"
	.string "Certains objets sont inutilisables\n"
	.string "selon l'endroit ou la situation.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Sélectionne la POCHE OBJ. RARES.\n"
	.string "{CIRCLE_2} Choisis un objet avec haut et bas\n"
	.string "sur la manette {PLUS}.\n"
	.string "{CIRCLE_3} Sélectionne UTILIS. pour utiliser\n"
	.string "l'objet sélectionné.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} Contre un POKéMON sauvage,\n"
	.string "sélectionne la POCHE POKé BALLS.\n"
	.string "{CIRCLE_2} Choisis une POKé BALL avec haut\n"
	.string "et bas sur la manette {PLUS}.\n"
	.string "{CIRCLE_3} Sélectionne UTILIS. pour lancer\n"
	.string "la POKé BALL sélectionnée.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Sélectionne {PLAYER} sur le menu.\n"
	.string "{CIRCLE_2} Ta CARTE DRESSEUR\n"
	.string "s'affiche avec les infos de base.\n"
	.string "Appuie sur le bouton A pour\n"
	.string "retourner la carte.\n"
	.string "{CIRCLE_3} Diverses infos sont visibles sur\n"
	.string "l'autre face.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Sélectionne SAUVER sur le menu.\n"
	.string "{CIRCLE_2} Sélectionne OUI pour\n"
	.string "sauvegarder ta progression.\n"
	.string "La console peut être éteinte une\n"
	.string "fois la partie sauvegardée. La\n"
	.string "partie reprend depuis la dernière\n"
	.string "sauvegarde.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Sélectionne OPTIONS sur le menu.\n"
	.string "{CIRCLE_2} Fais un choix avec haut et bas\n"
	.string "sur la manette {PLUS} et modifie les\n"
	.string "paramètres avec gauche et droite.\n"
	.string "{CIRCLE_3} Sélectionne RETOUR ou appuie\n"
	.string "sur le bouton B après avoir effectué\n"
	.string "des changements.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Ouvre le menu.\n"
	.string "{CIRCLE_2} Appuie sur haut ou bas sur\n"
	.string "la manette {PLUS} et sélectionne SAC.\n"
	.string "{CIRCLE_3} Sélectionne POTION dans la\n"
	.string "POCHE OBJETS.\n"
	.string "{CIRCLE_4} Sélectionne UTILIS.\n"
	.string "{CIRCLE_5} Sélectionne le POKéMON à soigner.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Ouvre le menu.\n"
	.string "{CIRCLE_2} Appuie sur haut ou bas sur\n"
	.string "la manette {PLUS} et sélectionne SAC.\n"
	.string "{CIRCLE_3} Appuie sur gauche ou droite pour\n"
	.string "ouvrir la POCHE OBJ. RARES et\n"
	.string "sélectionne la CARTE.\n"
	.string "{CIRCLE_4} Sélectionne UTILIS.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Ouvre le menu.\n"
	.string "{CIRCLE_2} Ouvre la POCHE OBJ. RARES.\n"
	.string "{CIRCLE_3} Sélectionne la BOITE CT.\n"
	.string "{CIRCLE_4} Sélectionne OUVRIR et utilise\n"
	.string "une CT.\n"
	.string "{CIRCLE_5} Sélectionne le POKéMON à\n"
	.string "qui enseigner la CT.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Ouvre le menu.\n"
	.string "{CIRCLE_2} Ouvre la POCHE OBJ. RARES\n"
	.string "dans le SAC.\n"
	.string "{CIRCLE_3} Sélectionne la BOITE CT.\n"
	.string "{CIRCLE_4} Sélectionne OUVRIR et utilise\n"
	.string "une CS.\n"
	.string "{CIRCLE_5} Sélectionne un POKéMON apte.$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Ouvre le menu.\n"
	.string "{CIRCLE_2} Sélectionne POKéMON.\n"
	.string "{CIRCLE_3} Sélectionne un POKéMON qui\n"
	.string "connaît une CS. Les CS sont indiquées\n"
	.string "en bleu. Choisis la CS désirée selon\n"
	.string "la situation (VOL, COUPE, etc).$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Ouvre le menu puis la POCHE\n"
	.string "OBJ. RARES dans le SAC et choisis\n"
	.string "BICYCLETTE.\n"
	.string "{CIRCLE_2} Sélectionne UTILIS. ou \n"
	.string "ENREGISTRE-la en appuyant sur\n"
	.string "SELECT.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Avec la manette {PLUS}, choisis une\n"
	.string "lettre et confirme avec le bouton A.\n"
	.string "{CIRCLE_2} Appuie sur le bouton B pour \n"
	.string "revenir en arrière.\n"
	.string "{CIRCLE_3} Appuie sur SELECT pour passer\n"
	.string "des majuscules aux minuscules.\n"
	.string "{CIRCLE_4} Valide ton nom avec OK.$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Dans un CENTRE POKéMON,\n"
	.string "mets-toi face à un PC et appuie sur\n"
	.string "le bouton A.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Sélectionne PC DE {STR_VAR_1} sur le PC.\n"
	.string "{CIRCLE_2} Sélectionne une des trois\n"
	.string "commandes pour accéder à la\n"
	.string "GESTION DE STOCKS DE POKéMON.\n"
	.string "Si tu attrapes un POKéMON en plus\n"
	.string "des six de ton équipe, il est envoyé\n"
	.string "directement dans une BOITE.$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Sélectionne un POKéMON dans la\n"
	.string "BOITE avec la manette {PLUS}.\n"
	.string "{CIRCLE_2} Sélectionne RETIRER pour\n"
	.string "l'ajouter dans ton équipe.\n"
	.string "Tu ne peux pas retirer de POKéMON\n"
	.string "si tu en as déjà six dans ton équipe.$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Sélectionne un POKéMON de ton\n"
	.string "équipe avec la manette {PLUS}.\n"
	.string "{CIRCLE_2} Sélectionne DEPOSER.\n"
	.string "{CIRCLE_3} Choisis une BOITE et appuie sur\n"
	.string "le bouton A pour déposer le POKéMON.\n"
	.string "Si tu n'as qu'un POKéMON, tu ne peux\n"
	.string "pas le déposer dans une BOITE.$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Sélectionne un POKéMON.\n"
	.string "{CIRCLE_2} Prends le POKéMON en \n"
	.string "sélectionnant DEPLACER et change-le\n"
	.string "de place avec la manette {PLUS}.\n"
	.string "{CIRCLE_3} Place le POKéMON sur le nom\n"
	.string "de la BOITE et appuie sur gauche\n"
	.string "ou droite pour changer de BOITE.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Les POKéMON apparaissant en\n"
	.string "transparence peuvent porter un objet\n"
	.string "sélectionné avec le bouton A.\n"
	.string "{CIRCLE_2} Les POKéMON apparaissant\n"
	.string "clairement peuvent donner l'objet\n"
	.string "qu'ils portent ou le déposer dans le\n"
	.string "SAC en appuyant sur le bouton A.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Sélectionne PC DE {PLAYER} sur\n"
	.string "le PC.\n"
	.string "{CIRCLE_2} Sélectionne STOCKAGE OBJ.\n"
	.string "ou BOITE LETTR.\n"
	.string "Tu peux utiliser ton PC pour stocker\n"
	.string "ou retirer des OBJETS selon la place\n"
	.string "restant dans ton SAC.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Sélectionne RETIRER OBJET.\n"
	.string "{CIRCLE_2} Sélectionne l'objet à retirer.\n"
	.string "{CIRCLE_3} L'objet peut être retiré ou placé\n"
	.string "dans la POCHE OBJET DU SAC.\n"
	.string "Il peut aussi être donné directement\n"
	.string "à un POKéMON pour être porté.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Sélectionne DEPOSER OBJET.\n"
	.string "{CIRCLE_2} Sélectionne l'objet du SAC à\n"
	.string "déposer avec la manette {PLUS}.\n"
	.string "{CIRCLE_3} S'il y a plus d'un objet à\n"
	.string "déposer, entre la quantité avec la\n"
	.string "manette {PLUS} et appuie sur le\n"
	.string "bouton A.$"

Help_Text_HowToUseMailbox::
	.string "Une LETTRE prise à un POKéMON\n"
	.string "est déposée dans la BOITE AUX\n"
	.string "LETTRES. Sans LETTRE, la BOITE\n"
	.string "n'est pas accessible.\n"
	.string "{CIRCLE_1} Sélectionne PC DE {PLAYER}.\n"
	.string "{CIRCLE_2} Sélectionne BOITE LETTR.\n"
	.string "pour lire une LETTRE ou la donner.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Sélectionne le PC DE CHEN.\n"
	.string "{CIRCLE_2} Le PROF. CHEN va évaluer\n"
	.string "ton POKéDEX.\n"
	.string "Ses évaluations vont te donner\n"
	.string "des indices pour attraper d'autres\n"
	.string "POKéMON.$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Appuie sur START.\n"
	.string "{CIRCLE_2} Le menu apparaît sur la droite.\n"
	.string "{CIRCLE_3} Selon la situation, le menu\n"
	.string "peut avoir différentes commandes.\n"
	.string "Le menu n'apparaît pas si tu\n"
	.string "marches, combats, etc.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Sélectionne ATTAQUE.\n"
	.string "{CIRCLE_2} Sélectionne une des capacités\n"
	.string "indiquées pour lancer une attaque.$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Sélectionne POKéMON.\n"
	.string "{CIRCLE_2} Sélectionne le POKéMON de\n"
	.string "ton équipe que tu veux utiliser.\n"
	.string "{CIRCLE_3} Si tu as deux POKéMON ou\n"
	.string "plus avec toi, tu peux changer leur\n"
	.string "position avec ECHANGER.\n"
	.string "Vérifie les données avec RESUME.$"

Help_Text_HowToUseShift::
	.string "Cette commande remplace le POKéMON\n"
	.string "au combat avec un autre de l'équipe.\n"
	.string "{CIRCLE_1} Choisis le POKéMON à envoyer.\n"
	.string "{CIRCLE_2} Sélectionne ECHANGER.\n"
	.string "{CIRCLE_3} Le POKéMON sélectionné va \n"
	.string "remplacer celui au combat.$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Sélectionne RESUME.\n"
	.string "{CIRCLE_2} Appuie sur gauche ou droite sur\n"
	.string "la manette {PLUS} pour choisir entre:\n"
	.string "INFOS POKéMON\n"
	.string "APTITUDES\n"
	.string "CAPACITES CONNUES$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Sélectionne SAC sur le menu.\n"
	.string "{CIRCLE_2} Appuie sur gauche ou droite sur\n"
	.string "la manette {PLUS} pour choisir entre:\n"
	.string "OBJETS\n"
	.string "OBJ. RARES\n"
	.string "POKé BALLS\n"
	.string "Choisis un objet avec bas ou haut.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} Les POKéMON déjà attrapés\n"
	.string "sont identifiés par une POKé BALL\n"
	.string "dans la liste du POKéDEX.\n"
	.string "{CIRCLE_2} Un POKéMON capturé fournit\n"
	.string "un grand nombre d'informations.\n"
	.string "{CIRCLE_3} Sélectionne SUIVANT pour afficher\n"
	.string "une CARTE des habitats du POKéMON.$"

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} A la maison, va droit au PC et\n"
	.string "appuie sur le bouton A.\n"
	.string "{CIRCLE_2} Le PC s'allume.\n"
	.string "{CIRCLE_3} Sélectionne STOCKAGE OBJ.\n"
	.string "ou BOITE LETTR.$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Sélectionne RETIRER OBJET\n"
	.string "pour prendre un objet du PC.\n"
	.string "{CIRCLE_2} Sélectionne DEPOSER OBJET\n"
	.string "pour mettre un objet de ton SAC\n"
	.string "dans le PC.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Sélectionne RETIRER OBJET.\n"
	.string "{CIRCLE_2} Sélectionne l'objet à retirer.\n"
	.string "{CIRCLE_3} L'objet peut être retiré ou placé\n"
	.string "dans la POCHE OBJET du SAC.\n"
	.string "Il peut aussi être donné directement\n"
	.string "à un POKéMON pour être porté.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Sélectionne DEPOSER OBJET.\n"
	.string "{CIRCLE_2} Sélectionne l'objet du SAC à\n"
	.string "déposer avec la manette {PLUS}.\n"
	.string "{CIRCLE_3} Cette commande ne peut pas\n"
	.string "être utilisée s'il n'y a rien dans le\n"
	.string "SAC.$"

Help_Text_HowToUseMailbox2::
	.string "Une LETTRE prise à un POKéMON\n"
	.string "est déposée dans la BOITE AUX\n"
	.string "LETTRES. Sans LETTRE, la BOITE\n"
	.string "n'est pas accessible.\n"
	.string "{CIRCLE_1} Sélectionne une LETTRE pour\n"
	.string "la lire ou donne-la à un POKéMON.$"

Help_Text_HowToUseRun::
	.string "Tu ne peux pas choisir FUITE dans\n"
	.string "un combat contre un DRESSEUR!\n"
	.string "{CIRCLE_1} La FUITE n'est possible que\n"
	.string "contre un POKéMON sauvage.\n"
	.string "{CIRCLE_2} Tes chances de fuir sont plus\n"
	.string "grandes si ton POKéMON est rapide.$"

Help_Text_HowToRegisterKeyItem::
	.string "Tu peux ENREGISTRER un objet rare\n"
	.string "pour l'utiliser instantanément en\n"
	.string "appuyant sur SELECT.\n"
	.string "{CIRCLE_1} Ouvre la POCHE OBJ. RARES.\n"
	.string "{CIRCLE_2} Choisis un objet, puis\n"
	.string "sélectionne ENREG.$"

Help_Text_HowToUseBall::
	.string "Pour lancer les POKé BALLS\n"
	.string "utilisées dans le PARC SAFARI.\n"
	.string "Quand un POKéMON sauvage apparaît,\n"
	.string "lance des SAFARI BALLS pour\n"
	.string "l'attraper!$"

Help_Text_HowToUseBait::
	.string "Pour lancer les appâts spéciaux\n"
	.string "utilisés au PARC SAFARI. C'est de\n"
	.string "la nourriture POKéMON mise en boule\n"
	.string "pour qu'ils la mangent facilement.\n"
	.string "Une fois l'appât lancé, les POKéMON\n"
	.string "sauvages sont attirés et ont moins de\n"
	.string "chances de fuir.$"

Help_Text_HowToUseRock::
	.string "Pour lancer une pierre au sol\n"
	.string "dans le PARC SAFARI.\n"
	.string "Cela peut faire fuir les POKéMON,\n"
	.string "mais dans le cas contraire, ils sont\n"
	.string "plus faciles à attraper!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Sélectionne PANTHEON sur le PC.\n"
	.string "{CIRCLE_2} Tu peux ensuite voir les POKéMON\n"
	.string "entrés au PANTHEON.$"

Help_Text_HP::
	.string "PV$"

Help_Text_EXP::
	.string "EXP.{LEFT_PAREN}Points EXP.{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "CAPACITES$"

Help_Text_Attack::
	.string "ATTAQUE$"

Help_Text_Defense::
	.string "DEFENSE$"

Help_Text_SpAtk::
	.string "ATQ. SPE.$"

Help_Text_SpDef::
	.string "DEF. SPE.$"

Help_Text_Speed::
	.string "VITESSE$"

Help_Text_Level::
	.string "N.{LEFT_PAREN}niveau{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TYPE $"

Help_Text_OT::
	.string "DO$"

Help_Text_Item::
	.string "OBJET$"

Help_Text_Ability::
	.string "CAPACITE SPE.$"

Help_Text_Money::
	.string "ARGENT$"

Help_Text_MoveType::
	.string "TYPE DE LA CAPACITE$"

Help_Text_Nature::
	.string "NATURE$"

Help_Text_IDNo::
	.string "NºID$"

Help_Text_PP::
	.string "PP$"

Help_Text_Power::
	.string "POUVOIR$"

Help_Text_Accuracy::
	.string "PRECISION$"

Help_Text_FNT::
	.string "KO$"

Help_Text_Items::
	.string "OBJETS$"

Help_Text_KeyItems::
	.string "OBJ. RARES$"

Help_Text_PokeBalls::
	.string "POKé BALLS$"

Help_Text_Pokedex::
	.string "POKéDEX$"

Help_Text_PlayTime::
	.string "DUREE JEU$"

Help_Text_Badges::
	.string "BADGES$"

Help_Text_TextSpeed::
	.string "VIT. TEXTE$"

Help_Text_BattleScene::
	.string "ANIMAT. COMBAT$"

Help_Text_BattleStyle::
	.string "STYLE COMBAT$"

Help_Text_Sound::
	.string "SON$"

Help_Text_ButtonMode::
	.string "MODE BOUTONS$"

Help_Text_Frame::
	.string "FENETRE$"

Help_Text_Cancel2::
	.string "RETOUR$"

Help_Text_TM::
	.string "CT$"

Help_Text_HM::
	.string "CS$"

Help_Text_HMMove::
	.string "CAPACITE CS$"

Help_Text_Evolution::
	.string "EVOLUTION$"

Help_Text_StatusProblem::
	.string "PROBLEME DE STATUT$"

Help_Text_Pokemon::
	.string "POKéMON$"

Help_Text_IDNo2::
	.string "NºID$"

Help_Text_Money2::
	.string "ARGENT$"

Help_Text_Badges2::
	.string "BADGES$"

Help_Text_DefineHP::
	.string "Les PV indiquent la vitalité des\n"
	.string "POKéMON. Si les PV d'un POKéMON\l"
	.string "tombent à zéro, il est KO et ne peut\l"
	.string "plus se battre. Tu gagnes un combat\l"
	.string "quand le POKéMON ennemi n'a\l"
	.string "plus de PV. Restaure les PV de tes\l"
	.string "POKéMON quand tu en as l'occasion.$"

Help_Text_DefineEXP::
	.string "Les points EXP. correspondent aux\n"
	.string "points d'expérience d'un POKéMON.\l"
	.string "Accumule les points EXP. en gagnant\l"
	.string "des combats pour faire monter le\l"
	.string "niveau de tes POKéMON. La jauge\l"
	.string "EXP. se remet à zéro quand un \l"
	.string "POKéMON change de niveau.$"

Help_Text_DefineMoves::
	.string "Les POKéMON peuvent apprendre\n"
	.string "jusqu'à quatre techniques, ou\l"
	.string "capacités. Certaines servent\l"
	.string "seulement à attaquer et d'autres ont\l"
	.string "des effets spéciaux. Les types de\l"
	.string "capacités qui peuvent être apprises\l"
	.string "dépendent du POKéMON.$"

Help_Text_DefineAttack::
	.string "ATTAQUE indique la puissance\n"
	.string "offensive d'une capacité. Plus cette\l"
	.string "stat est élevée, et plus le coup\l"
	.string "est  puissant. Cela s'applique aux\l"
	.string "types suivants: NORMAL, VOL,\l"
	.string "POISON, SOL, INSECTE, COMBAT,\l"
	.string "ROCHE, SPECTRE et ACIER.$"

Help_Text_DefineDefense::
	.string "DEFENSE indique la résistance d'un\n"
	.string "POKéMON aux attaques physiques.\l"
	.string "Plus cette stat est élevée, et moins\l"
	.string "les attaques physiques infligent\l"
	.string "de dégâts.$"

Help_Text_DefineSpAtk::
	.string "ATQ. SPE. (attaque spéciale) indique\n"
	.string "la puissance d'une capacité spéciale.\l"
	.string "Plus cette stat est élevée, et plus\l"
	.string "l'attaque spéciale est puissante.\l"
	.string "Cela s'applique aux types suivants:\l"
	.string "FEU, EAU, ELECTRIK, PLANTE, GLACE,\l"
	.string "PSY, DRAGON et TENEBRES.$"

Help_Text_DefineSpDef::
	.string "DEF. SPE. (défense spéciale) indique\n"
	.string "la résistance d'un POKéMON aux\l"
	.string "attaques spéciales. Plus cette stat\l"
	.string "est élevée, et moins les attaques\l"
	.string "spéciales infligent de dégâts.$"

Help_Text_DefineSpeed::
	.string "VITESSE indique l'agilité d'un\n"
	.string "POKéMON. Si cette stat est\l"
	.string "supérieure à celle de ton adversaire,\l"
	.string "ton POKéMON peut utiliser une\l"
	.string "capacité en premier.$"

Help_Text_DefineLevel::
	.string "N. (niveau) indique la croissance et\n"
	.string "la force d'un POKéMON. Quand le\l"
	.string "niveau monte, cela augmente PV,\l"
	.string "ATTAQUE et DEFENSE, rendant le\l"
	.string "POKéMON plus fort. En changeant\l"
	.string "de niveau, un POKéMON peut\l"
	.string "apprendre de nouvelles capacités.$"

Help_Text_DefineType::
	.string "Les POKéMON et capacités sont\n"
	.string "classés par type. Chaque type a des\l"
	.string "avantages et des inconvénients contre\l"
	.string "d'autres types. Comme dans le jeu\l"
	.string "pierre, papier, ciseaux, le type EAU\l"
	.string "est fort contre le FEU et faible\l"
	.string "contre le type PLANTE.$"

Help_Text_DefineOT::
	.string "DO signifie DRESSEUR ORIGINAL, le\n"
	.string "premier DRESSEUR à avoir attrapé le\l"
	.string "POKéMON sélectionné. Ce nom reste\l"
	.string "même quand le POKéMON est \l"
	.string "échangé.$"

Help_Text_DefineItem::
	.string "Chaque POKéMON peut porter un\n"
	.string "objet. Certains objets sont utilisés\l"
	.string "automatiquement selon la situation.\l"
	.string "Pour faire tenir un objet à un\l"
	.string "POKéMON, choisis-en un dans ton\l"
	.string "SAC et sélectionne DONNER pour\l"
	.string "qu'un POKéMON le porte.$"

Help_Text_DefineAbility::
	.string "Tous les POKéMON ont une capacité\n"
	.string "spéciale. Il existe plusieurs types\l"
	.string "de capacités, toutes ne sont pas\l"
	.string "utilisées au combat. Les capacités\l"
	.string "diffèrent d'une espèce à l'autre.\l"
	.string "Certaines espèces peuvent avoir\l"
	.string "plus d'un type de capacité.$"

Help_Text_DefineMoney::
	.string "Tu reçois de l'argent chaque fois\n"
	.string "que tu remportes un combat contre\l"
	.string "un DRESSEUR. Economise pour\l"
	.string "pouvoir acheter des objets dans les\l"
	.string "BOUTIQUES POKéMON.$"

Help_Text_DefineMoveType::
	.string "Les capacités sont classées par type.\n"
	.string "La puissance d'une attaque est\l"
	.string "boostée si son type est le même que\l"
	.string "celui du POKéMON. Si le type d'une\l"
	.string "capacité prend l'avantage sur le type\l"
	.string "de la cible, son efficacité est aussi\l"
	.string "boostée.$"

Help_Text_DefineNature::
	.string "Tous les POKéMON ont une\n"
	.string "personnalité, ou NATURE. La nature\l"
	.string "d'un POKéMON affecte la façon dont\l"
	.string "celui-ci monte de niveau.$"

Help_Text_DefineIDNo::
	.string "Le NºID est un numéro d'identification\n"
	.string "attribué à chaque DRESSEUR. Il est\l"
	.string "utilisé avec le nom du DO pour\l"
	.string "identifier le DRESSEUR ORIGINAL.\l"
	.string "Le NºID ne change pas même\l"
	.string "si le POKéMON est échangé.$"

Help_Text_DefinePP::
	.string "Les PP correspondent aux points de\n"
	.string "puissance. Ils indiquent le nombre de\l"
	.string "fois qu'une capacité peut être\l"
	.string "utilisée dans un combat. Comme les\l"
	.string "PV, les PP peuvent être restaurés\l"
	.string "dans un  CENTRE POKéMON.$"

Help_Text_DefinePower::
	.string "POUVOIR indique la force d'une\n"
	.string "attaque. Plus ce chiffre est grand,\l"
	.string "et plus les dégâts infligés à la\l"
	.string "cible sont importants.$"

Help_Text_DefineAccuracy::
	.string "PRECISION indique la probabilité\n"
	.string "d'une attaque à toucher sa cible.\l"
	.string "Plus ce nombre est grand, et plus les\l"
	.string "chances de toucher la cible sont\l"
	.string "importantes.$"

Help_Text_DefineFNT::
	.string "KO apparaît quand un POKéMON\n"
	.string "ne peut plus combattre. Un POKéMON\l"
	.string "est incapable de se battre si ses PV\l"
	.string "atteignent zéro. Ranime un POKéMON\l"
	.string "KO en allant dans un CENTRE POKéMON\l"
	.string "ou en utilisant un objet.$"

Help_Text_DefineItems::
	.string "Les objets achetés dans les\n"
	.string "BOUTIQUES POKéMON sont rangés\l"
	.string "dans la POCHE OBJETS. Les objets\l"
	.string "peuvent être utilisés, donnés à\l"
	.string "porter aux POKéMON ou jetés\l"
	.string "aux ordures.$"

Help_Text_DefineKeyItems::
	.string "Les objets importants trouvés ou \n"
	.string "reçus sont placés dans la\l"
	.string "POCHE OBJ. RARES. Les objets\l"
	.string "rares peuvent être utilisés ou\l"
	.string "enregistrés pour être pris\l"
	.string "directement avec SELECT sans devoir\l"
	.string "ouvrir le SAC.$"

Help_Text_DefinePokeBalls::
	.string "Les POKé BALLS, qui servent à\n"
	.string "attraper les POKéMON, sont placées\l"
	.string "dans la POCHE POKé BALLS. Elles\l"
	.string "s'achètent dans les BOUTIQUES\l"
	.string "POKéMON. Elles peuvent être\l"
	.string "utilisées, données à porter aux\l"
	.string "POKéMON ou jetées aux ordures.$"

Help_Text_DefinePokedex::
	.string "Indique le nombre d'espèces de\n"
	.string "POKéMON attrapées et/ou qui ont\l"
	.string "évolué pour remplir le POKéDEX.\l"
	.string "Fais de ton mieux pour tous\l"
	.string "les attraper!$"

Help_Text_DefinePlayTime::
	.string "C'est le temps total que tu as\n"
	.string "passé à jouer.$"

Help_Text_DefineBadges::
	.string "Les BADGES DE LA LIGUE POKéMON\n"
	.string "que tu as gagnés sont enregistrés et\l"
	.string "exposés. Gagne des BADGES en\l"
	.string "affrontant les CHAMPIONS D'ARENE\l"
	.string "dans chaque ville.$"

Help_Text_DefineTextSpeed::
	.string "Pour choisir la vitesse de défilement\n"
	.string "du texte. Tu peux choisir entre trois\l"
	.string "vitesses différentes.$"

Help_Text_DefineBattleScene::
	.string "Tu peux choisir de voir ou non les\n"
	.string "animations des combats.$"

Help_Text_DefineBattleStyle::
	.string "Pour choisir si un DRESSEUR peut\n"
	.string "changer ou non de POKéMON après\l"
	.string "avoir mis un POKéMON adverse KO.\l"
	.string "Sélectionne CHOIX si tu veux pouvoir\l"
	.string "changer de POKéMON après un combat.$"

Help_Text_DefineSound::
	.string "Pour choisir entre MONO et STEREO.$"

Help_Text_DefineButtonMode::
	.string "AIDE pour afficher les messages\n"
	.string "d'aide avec les boutons L ou R.\l"
	.string "LR pour changer les pages du\l"
	.string "POKéDEX et les POCHES DU SAC\l"
	.string "avec les boutons L et R.\l"
	.string "L=A pour que le bouton L ait la\l"
	.string "même fonction que le bouton A.$"

Help_Text_DefineFrame::
	.string "Tu peux choisir la forme de la\n"
	.string "fenêtre autour des menus. Essaie\l"
	.string "un peu et choisis ta préférée.$"

Help_Text_DefineCancel2::
	.string "Les paramètres correspondront aux\n"
	.string "sélections indiquées en rouge, tu\l"
	.string "retourneras au menu.$"

Help_Text_DefineTM::
	.string "Une CT (Capsule Technique) sert à\n"
	.string "enseigner des capacités aux POKéMON.\l"
	.string "Il en existe plusieurs sortes.\l"
	.string "Seuls les POKéMON aptes sont\l"
	.string "capables de les apprendre.\l"
	.string "Une CT n'est utilisable qu'une\l"
	.string "seule fois.$"

Help_Text_DefineHM::
	.string "Une CS (Capsule Secrète) sert à\n"
	.string "enseigner des capacités SECRETES.\l"
	.string "Seuls les POKéMON aptes sont\l"
	.string "capables d'utiliser une CS.\l"
	.string "Contrairement aux CT, les CS sont\l"
	.string "utilisables plusieurs fois, mais elles\l"
	.string "sont dures à oublier.$"

Help_Text_DefineHMMove::
	.string "Les capacités SECRETES sont\n"
	.string "indispensables pour progresser \l"
	.string "dans le jeu. Pour les utiliser hors\l"
	.string "d'un combat, même avec un POKéMON\l"
	.string "KO, ouvre le menu “POKéMON” et\l"
	.string "choisis le POKéMON connaissant\l"
	.string "la capacité désirée. $"

Help_Text_DefineEvolution::
	.string "Parmi les POKéMON, certains\n"
	.string "connaissent de grands changements\l"
	.string "(évolution) en changeant de niveau.\l"
	.string "Quand ils évoluent en changeant de\l"
	.string "niveau ou pour d'autres raisons, les\l"
	.string "POKéMON changent de forme et peuvent\l"
	.string "apprendre de nouvelles capacités.$"

Help_Text_DefineStatusProblem::
	.string "Les problèmes de statut sont:\n"
	.string "Sommeil: Attaques inutilisables.\l"
	.string "Poison: Perte progressive des PV.\l"
	.string "Paralysie: Peut empêcher d'attaquer.\l"
	.string "Brûlure: Perte de PV, baisse ATTAQ.\l"
	.string "Gel: Attaques inutilisables.\l"
	.string "Ils sont soignables par des objets.$"

Help_Text_DefinePokemon::
	.string "POKéMON est le nom donné à ces\n"
	.string "créatures incroyables qui habitent\l"
	.string "aux quatre coins du monde.\l"
	.string "Les gens les dressent pour leur\l"
	.string "tenir compagnie mais aussi pour\l"
	.string "combattre ou pour bien d'autres\l"
	.string "choses.$"

Help_Text_DefineIDNo2::
	.string "Le NºID est un numéro d'identification\n"
	.string "attribué à chaque DRESSEUR. Il est\l"
	.string "utilisé avec le nom du DO pour\l"
	.string "identifier le DRESSEUR ORIGINAL.\l"
	.string "Le NºID ne change pas même\l"
	.string "si le POKéMON est échangé.$"

Help_Text_DefineMoney2::
	.string "Tu reçois de l'argent chaque fois\n"
	.string "que tu remportes un combat contre\l"
	.string "un DRESSEUR. Economise pour\l"
	.string "pouvoir acheter des objets dans les\l"
	.string "BOUTIQUES POKéMON.$"

Help_Text_DefineBadges2::
	.string "Indique le nombre de BADGES DE\n"
	.string "LIGUE POKéMON que tu as gagnés.\l"
	.string "Remporte les combats contre les\l"
	.string "CHAMPIONS d'ARENE de chaque ville\l"
	.string "pour gagner ces BADGES.$"

Help_Text_TheHelpSystem::
	.string "Système d'AIDE$"

Help_Text_TheGame::
	.string "Le jeu$"

Help_Text_WirelessAdapter::
	.string "Adaptateur sans fil GBA$"

Help_Text_GameFundamentals1::
	.string "Bases du jeu 1$"

Help_Text_GameFundamentals2::
	.string "Bases du jeu 2$"

Help_Text_GameFundamentals3::
	.string "Bases du jeu 3$"

Help_Text_WhatArePokemon::
	.string "Qu'est-ce qu'un POKéMON?$"

Help_Text_DescTheHelpSystem::
	.string "Les messages d'aide changent\n"
	.string "selon ta progression dans le jeu.\l"
	.string "Ils sont conçus pour t'aider selon\l"
	.string "tes besoins. Utilise le système\l"
	.string "d'AIDE s'il y a quelque chose que\l"
	.string "tu ne comprends pas.$"

Help_Text_DescTheGame::
	.string "Tu incarnes le personnage principal\n"
	.string "du jeu parti explorer le monde des\l"
	.string "POKéMON. En parlant aux gens\l"
	.string "et en résolvant des énigmes, tu\l"
	.string "ouvriras de nouvelles voies. Tu\l"
	.string "pourras compter sur tes POKéMON\l"
	.string "pour finir ta quête.$"

Help_Text_DescWirelessAdapter::
	.string "Ce jeu utilise un adaptateur sans fil\n"
	.string "GBA pour communiquer en réseau.\p"
	.string "Tu peux te connecter n'importe quand\n"
	.string "et avec n'importe qui!\p"
	.string "Essaie de jouer en gardant toujours\n"
	.string "l'adaptateur sans fil GBA branché!$"

Help_Text_DescGameFundamentals1::
	.string "Visite chaque ville, voyage sur\n"
	.string "toutes les routes, explore chaque\l"
	.string "grotte et affronte tous les\l"
	.string "DRESSEURS pour devenir le\l"
	.string "plus grand DRESSEUR POKéMON!$"

Help_Text_DescGameFundamentals2::
	.string "Dans ton aventure, tu devras\n"
	.string "faire face à de nombreux obstacles\l"
	.string "que tu pourras contourner en\l"
	.string "résolvant des énigmes ou en\l"
	.string "accomplissant certaines choses,\l"
	.string "même très éloignées.$"

Help_Text_DescGameFundamentals3::
	.string "Certains obstacles ne peuvent\n"
	.string "être franchis que lorsque tes\l"
	.string "POKéMON apprennent des capacités\l"
	.string "spécifiques.$"

Help_Text_DescWhatArePokemon::
	.string "Les POKéMON sont des créatures\n"
	.string "entourées de mystère. On peut les\l"
	.string "voir dans les herbes, la mer ou les \l"
	.string "grottes. Ils obéissent au DRESSEUR\l"
	.string "qui les a attrapés.$"

Help_Text_UsingTypeMatchupList::
	.string "Utiliser la liste des rapports$"

Help_Text_OwnMoveDark::
	.string "Type de la capacité: TENEBRES$"

Help_Text_OwnPokemonDark::
	.string "Type du POKéMON: TENEBRES$"

Help_Text_OwnMoveRock::
	.string "Type de la capacité: ROCHE$"

Help_Text_OwnPokemonRock::
	.string "Type du POKéMON: ROCHE$"

Help_Text_OwnMovePsychic::
	.string "Type de la capacité: PSY$"

Help_Text_OwnPokemonPsychic::
	.string "Type du POKéMON: PSY$"

Help_Text_OwnMoveFighting::
	.string "Type de la capacité: COMBAT$"

Help_Text_OwnPokemonFighting::
	.string "Type du POKéMON: COMBAT$"

Help_Text_OwnMoveGrass::
	.string "Type de la capacité: PLANTE$"

Help_Text_OwnPokemonGrass::
	.string "Type du POKéMON: PLANTE$"

Help_Text_OwnMoveGhost::
	.string "Type de la capacité: SPECTRE$"

Help_Text_OwnPokemonGhost::
	.string "Type du POKéMON: SPECTRE$"

Help_Text_OwnMoveIce::
	.string "Type de la capacité: GLACE$"

Help_Text_OwnPokemonIce::
	.string "Type du POKéMON: GLACE$"

Help_Text_OwnMoveGround::
	.string "Type de la capacité: SOL$"

Help_Text_OwnPokemonGround::
	.string "Type du POKéMON: SOL$"

Help_Text_OwnMoveElectric::
	.string "Type de la capacité: ELECTRIK$"

Help_Text_OwnPokemonElectric::
	.string "Type du POKéMON: ELECTRIK$"

Help_Text_OwnMovePoison::
	.string "Type de la capacité: POISON$"

Help_Text_OwnPokemonPoison::
	.string "Type du POKéMON: POISON$"

Help_Text_OwnMoveDragon::
	.string "Type de la capacité: DRAGON$"

Help_Text_OwnPokemonDragon::
	.string "Type du POKéMON: DRAGON$"

Help_Text_OwnMoveNormal::
	.string "Type de la capacité: NORMAL$"

Help_Text_OwnPokemonNormal::
	.string "Type du POKéMON: NORMAL$"

Help_Text_OwnMoveSteel::
	.string "Type de la capacité: ACIER$"

Help_Text_OwnPokemonSteel::
	.string "Type du POKéMON: ACIER$"

Help_Text_OwnMoveFlying::
	.string "Type de la capacité: VOL$"

Help_Text_OwnPokemonFlying::
	.string "Type du POKéMON: VOL$"

Help_Text_OwnMoveFire::
	.string "Type de la capacité: FEU$"

Help_Text_OwnPokemonFire::
	.string "Type du POKéMON: FEU$"

Help_Text_OwnMoveWater::
	.string "Type de la capacité: EAU$"

Help_Text_OwnPokemonWater::
	.string "Type du POKéMON: EAU$"

Help_Text_OwnMoveBug::
	.string "Type de la capacité: INSECTE$"

Help_Text_OwnPokemonBug::
	.string "Type du POKéMON: INSECTE$"

Help_Text_HowToUseTypeMatchupList::
	.string "L'efficacité d'une attaque varie selon\n"
	.string "les rapports entre les POKéMON\l"
	.string "et leurs capacités:\l"
	.string "{CIRCLE_DOT}: Super efficace\l"
	.string "{TRIANGLE}: Pas très efficace\l"
	.string "{BIG_MULT_X}: Inefficace\l"
	.string "(Pas de chang. pour autres rapports).$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PSY, SPECTRE\p"
	.string "   {TRIANGLE}: COMBAT, TENEBRES, ACIER$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\l"
	.string "   {CIRCLE_DOT}: COMBAT, INSECTE\p"
	.string "   {TRIANGLE}: SPECTRE, TENEBRES\p"
	.string "   {BIG_MULT_X}: PSY$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: FEU, GLACE, VOL, INSECTE\p"
	.string "   {TRIANGLE}: COMBAT, SOL, ACIER$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\l"
	.string "   {CIRCLE_DOT}: EAU, PLANTE, COMBAT,\l"
	.string "        SOL, ACIER\p"
	.string "   {TRIANGLE}: NORMAL, FEU, POISON, VOL$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: COMBAT, POISON\p"
	.string "   {TRIANGLE}: PSY, ACIER\p"
	.string "   {BIG_MULT_X}: TENEBRES$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: INSECTE, SPECTRE, TENEBRES\p"
	.string "   {TRIANGLE}: COMBAT, PSY$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: NORMAL, GLACE, ROCHE,\n"
	.string "        TENEBRES, ACIER\l"
	.string "   {TRIANGLE}: POISON, VOL, PSY, INSECTE\p"
	.string "   {BIG_MULT_X}: SPECTRE$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: VOL, PSY\p"
	.string "   {TRIANGLE}: INSECTE, ROCHE, TENEBRES$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: EAU, SOL, ROCHE\p"
	.string "   {TRIANGLE}: FEU, PLANTE, POISON, VOL,\n"
	.string "        INSECTE, DRAGON, ACIER$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: FEU, GLACE, POISON, VOL,\n"
	.string "        INSECTE\l"
	.string "   {TRIANGLE}: EAU, ELECTRIK, PLANTE, SOL$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PSY, SPECTRE\p"
	.string "   {TRIANGLE}: TENEBRES, ACIER\p"
	.string "   {BIG_MULT_X}: NORMAL$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\l"
	.string "   {CIRCLE_DOT}: SPECTRE, TENEBRES\p"
	.string "   {TRIANGLE}: POISON, INSECTE\p"
	.string "   {BIG_MULT_X}: NORMAL, COMBAT$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PLANTE, SOL, VOL, DRAGON\p"
	.string "   {TRIANGLE}: FEU, EAU, GLACE, ACIER$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: FEU, COMBAT, ROCHE, ACIER\p"
	.string "   {TRIANGLE}: GLACE$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: FEU, ELECTRIK, POISON,\n"
	.string "        ROCHE, ACIER\p"
	.string "   {TRIANGLE}: PLANTE, INSECTE\n"
	.string "   {BIG_MULT_X}: VOL$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: EAU, PLANTE, GLACE\p"
	.string "   {TRIANGLE}: POISON, ROCHE\p"
	.string "   {BIG_MULT_X}: ELECTRIK$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: EAU, VOL\p"
	.string "   {TRIANGLE}: ELECTRIK, PLANTE, DRAGON\p"
	.string "   {BIG_MULT_X}: SOL$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: SOL\p"
	.string "   {TRIANGLE}: ELECTRIK, VOL, ACIER$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PLANTE\p"
	.string "   {TRIANGLE}: POISON, SOL, ROCHE, SPECTRE\p"
	.string "   {BIG_MULT_X}: ACIER$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: SOL, PSY\p"
	.string "   {TRIANGLE}: PLANTE, COMBAT, POISON,\n"
	.string "        INSECTE$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: DRAGON\p"
	.string "   {TRIANGLE}: ACIER$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: GLACE, DRAGON\p"
	.string "   {TRIANGLE}: FEU, EAU, ELECTRIK, PLANTE$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {TRIANGLE}: ROCHE, ACIER\p"
	.string "   {BIG_MULT_X}: SPECTRE$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: COMBAT\p"
	.string "   {BIG_MULT_X}: SPECTRE$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: GLACE, ROCHE\p"
	.string "   {TRIANGLE}: FEU, EAU, ELECTRIK, ACIER$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\l"
	.string "   {CIRCLE_DOT}: FEU, COMBAT, SOL\l"
	.string "   {TRIANGLE}: NORMAL, PLANTE, GLACE, VOL,\l"
	.string "        PSY, INSECTE, ROCHE, ACIER,\l"
	.string "        DRAGON, TENEBRES, SPECTRE\l"
	.string "   {BIG_MULT_X}: POISON$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PLANTE, COMBAT, INSECTE\p"
	.string "   {TRIANGLE}: ELECTRIK, ROCHE, ACIER$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\l"
	.string "   {CIRCLE_DOT}: ELECTRIK, GLACE, ROCHE\p"
	.string "   {TRIANGLE}: PLANTE, COMBAT, INSECTE\p"
	.string "   {BIG_MULT_X}: SOL$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PLANTE, GLACE, INSECTE,\n"
	.string "        ACIER\p"
	.string "   {TRIANGLE}: FEU, EAU, ROCHE, DRAGON$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: EAU, SOL, ROCHE\p"
	.string "   {TRIANGLE}: FEU, PLANTE, GLACE,\n"
	.string "        INSECTE, ACIER$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: FEU, SOL, ROCHE\p"
	.string "   {TRIANGLE}: EAU, PLANTE, DRAGON$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: ELECTRIK, PLANTE\p"
	.string "   {TRIANGLE}: FEU, EAU, GLACE, ACIER$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Effet sur le POKéMON adverse:\p"
	.string "   {CIRCLE_DOT}: PLANTE, PSY, TENEBRES\p"
	.string "   {TRIANGLE}: FEU, COMBAT, POISON,\n"
	.string "        VOL, SPECTRE, ACIER$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Effet de la capacité ennemie sur\n"
	.string "ton POKéMON:\p"
	.string "   {CIRCLE_DOT}: FEU, VOL, ROCHE\p"
	.string "   {TRIANGLE}: PLANTE, COMBAT, SOL$"
