gOtherText_NewName::
	.string "NOM:$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "YAN$"

gNameChoice_Kaz::
	.string "MAEL$"

gNameChoice_Toru::
	.string "DAVY$"

gNameChoice_Ash::
	.string "DANNY$"

gNameChoice_Kene::
	.string "GURVAN$"

gNameChoice_Geki::
	.string "GONTRAN$"

gNameChoice_Jak::
	.string "POLO$"

gNameChoice_Janne::
	.string "ZACK$"

gNameChoice_Jonn::
	.string "MARIO$"

gNameChoice_Kamon::
	.string "LORIS$"

gNameChoice_Karl::
	.string "MAX$"

gNameChoice_Taylor::
	.string "DAMIEN$"

gNameChoice_Oscar::
	.string "TOM$"

gNameChoice_Hiro::
	.string "GREG$"

gNameChoice_Max::
	.string "KAMEL$"

gNameChoice_Jon::
	.string "FRANCK$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "AYRTON$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "VINCE$"

gNameChoice_Omi::
	.string "JOANNA$"

gNameChoice_Jodi::
	.string "LUCIE$"

gNameChoice_Amanda::
	.string "EDITH$"

gNameChoice_Hillary::
	.string "PAULINE$"

gNameChoice_Makey::
	.string "EMMA$"

gNameChoice_Michi::
	.string "AUDREY$"

gNameChoice_Paula::
	.string "MARION$"

gNameChoice_June::
	.string "SAYAKA$"

gNameChoice_Cassie::
	.string "INGRID$"

gNameChoice_Rey::
	.string "LINDA$"

gNameChoice_Seda::
	.string "FLO$"

gNameChoice_Kiko::
	.string "YUKI$"

gNameChoice_Mina::
	.string "CARMEN$"

gNameChoice_Norie::
	.string "NOLWEEN$"

gNameChoice_Sai::
	.string "NADIA$"

gNameChoice_Momo::
	.string "HELENE$"

gNameChoice_Suzi::
	.string "CARO$"

gControlsGuide_Text_Intro::
	.string "Les différents boutons seront\n"
	.string "décrits par ordre d'importance.$"

gControlsGuide_Text_DPad::
	.string "Déplacer le personnage.\n"
	.string "Faire une sélection.$"

gControlsGuide_Text_AButton::
	.string "Confirmer un choix, observer,\n"
	.string "parler et faire défiler le texte.$"

gControlsGuide_Text_BButton::
	.string "Quitter, annuler un choix ou\n"
	.string "un mode.$"

gControlsGuide_Text_StartButton::
	.string "Ouvrir le menu.$"

gControlsGuide_Text_SelectButton::
	.string "Changer les objets ou utiliser\n"
	.string "un objet enregistré.$"

gControlsGuide_Text_LRButtons::
	.string "Obtenir de l'aide ou des\n"
	.string "explications pendant la partie.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Maintenant dis-moi. Es-tu un\n"
	.string "garçon ou une fille?$"

gPikachuIntro_Text_Page1::
	.string "Prépare-toi à te lancer dans une\n"
	.string "grande aventure, à la découverte\n"
	.string "d'un nouveau monde.\n"
	.string "\n"
	.string "Tu vas faire de nouvelles rencontres\n"
	.string "et découvrir de nouvelles villes.\n"
	.string "Profites-en pour récolter autant\n"
	.string "d'informations que possible.$"

gPikachuIntro_Text_Page2::
	.string "En résolvant des mystères et en aidant\n"
	.string "les gens, tu pourras ouvrir de\n"
	.string "nouvelles voies.\n"
	.string "\n"
	.string "Attends-toi à te faire défier par de\n"
	.string "nombreux DRESSEURS et à\n"
	.string "affronter des créatures sauvages.\n"
	.string "Sois brave et ne perds pas espoir.$"

gPikachuIntro_Text_Page3::
	.string "Nous espérons que tu rencontreras\n"
	.string "toutes sortes de gens pendant ce\n"
	.string "voyage et que tu prendras\n"
	.string "goût à la découverte.\n"
	.string "C'est notre objectif principal.\n"
	.string "\n"
	.string "Appuie sur le bouton A et plonge\n"
	.string "dans cette nouvelle aventure.$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Bien le bonjour! Bienvenue dans le\n"
	.string "monde incroyable des POKéMON!\p"
	.string "Mon nom est CHEN!\p"
	.string "Les gens m'appellent amicalement\n"
	.string "le PROF. POKéMON!\p"
	.string "$"

gOakSpeech_Text_ThisWorld::
	.string "Ce monde…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "… est peuplé de créatures\n"
	.string "appelées POKéMON!\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon::
	.string "Pour certains, les POKéMON sont des\n"
	.string "animaux domestiques, pour d'autres,\l"
	.string "ils sont un moyen de combattre.\p"
	.string "Pour ma part…\p"
	.string "L'étude des POKéMON est ma\n"
	.string "profession.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Mais avant tout, parle-moi\n"
	.string "un peu de toi.\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Comment t'appelles-tu?\p"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "D'accord…\n"
	.string "Donc tu t'appelles {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Voici mon petit-fils.\p"
	.string "Vous êtes rivaux depuis votre\n"
	.string "tendre enfance.\p"
	.string "… Heu…\n"
	.string "C'est quoi donc son nom déjà?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Tu le connais, n'est-ce pas?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "Euh, c'est bien {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "Mais oui, bien sûr que je m'en\n"
	.string "souviens, c'est {RIVAL}!\p"
	.string "$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Ta quête des POKéMON est sur le\n"
	.string "point de commencer!\p"
	.string "Un tout nouveau monde de rêves,\n"
	.string "d'aventures et de POKéMON t'attend!\l"
	.string "Bonne chance!$"
