Text_ObtainedTheX::
	.string "Obtenu: {STR_VAR_2}!$"

Text_BagIsFull::
	.string "Le SAC est plein…$"

Text_PutItemAway::
	.string "{PLAYER} met {STR_VAR_2} dans\n"
	.string "{STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} trouve {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Dommage!\n"
	.string "Le SAC est plein.$"

Text_FoundXCoins::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} met les JETONS\n"
	.string "dans la BOITE JETONS.$"

Text_CoinCaseIsFull::
	.string "Dommage!\n"
	.string "La BOITE JETONS est pleine.$"

Text_NothingToPutThemIn::
	.string "Dommage!\n"
	.string "Il n'y a rien pour les ranger.$"

Text_FoundXItems::
	.string "{PLAYER} a trouvé\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)$"

Text_ObtainedTheDecor::
	.string "Obtenu: {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Dommage! Il n'y a plus assez de\n"
	.string "place pour {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "Transfert de {STR_VAR_2} sur\n"
	.string "le PC.$"
