Text_MonSentToBoxInSomeonesPC::
	.string "{STR_VAR_2} a été transféré sur le\n"
	.string "PC de ???.\p"
	.string "Il a été placé dans la BOITE\n"
	.string "appelée “{STR_VAR_1}”.$"

Text_MonSentToBoxInBillsPC::
	.string "{STR_VAR_2} a été transféré sur le\n"
	.string "PC de LEO.\p"
	.string "Il a été placé dans la BOITE\n"
	.string "appelée “{STR_VAR_1}”.$"

Text_MonSentToBoxSomeonesBoxFull::
	.string "La BOITE {STR_VAR_3} sur le PC\n"
	.string "de ??? est pleine.\p"
	.string "{STR_VAR_2} a été placé dans la\n"
	.string "BOITE appelée “{STR_VAR_1}”.$"

Text_MonSentToBoxBillsBoxFull::
	.string "La BOITE {STR_VAR_3} sur le PC\n"
	.string "de LEO est pleine.\p"
	.string "{STR_VAR_2} a été placé dans la\n"
	.string "BOITE appelée “{STR_VAR_1}”.$"

Text_PlayerObtainedTheMon::
	.string "{PLAYER} obtient\n"
	.string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
	.string "ポケモンを　もちきれないので\n"
	.string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
	.string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
	.string "Il n'y a plus de place pour\n"
	.string "les POKéMON.\p"
	.string "Les BOITES sont pleines et\n"
	.string "ne peuvent plus rien recevoir.$"
