Text_CardKeyOpenedDoor::
	.string "Bingo!\n"
	.string "La CARTE MAGN. a ouvert la porte!$"

Text_ItNeedsCardKey::
	.string "Zut!\n"
	.string "Il faut une CARTE MAGN.!$"

Text_AccessedProfOaksPC::
	.string "Connexion au PC du PROF. CHEN.\p"
	.string "Accès au système d'évaluation\n"
	.string "du POKéDEX.$"

Text_HavePokedexRated::
	.string "Voulez-vous faire évaluer votre\n"
	.string "POKéDEX?$"

Text_ClosedLinkToProfOaksPC::
	.string "PC du PROF. CHEN. Déconnexion…$"

Text_VoiceRangOutDontRunAway::
	.string "Une voix:\n"
	.string "“Ne fuis pas!”$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight::
	.string "それっ　ちがうよー！$"

Text_ISee::
	.string "そっか‥$"

Text_TheDoorIsClosed::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen::
	.string "La porte est ouverte…$"
