Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POTE POKéMON: Le combattant le\n"
	.string "plus rapide attaque en premier.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "On dirait que mon RATTATA a\n"
	.string "été plus rapide que le ROUCOOL.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Les combattants attaquent à tour\n"
	.string "de rôle pour réduire les PV de\p"
	.string "leur adversaire.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Mon RATTATA a réduit les PV du\n"
	.string "POKéMON ennemi à zéro:\p"
	.string "c'est le gagnant!\p"
	.string "Les POKéMON qui participent au\n"
	.string "combat gagnent des points EXP.\p"
	.string "Quand un POKéMON a assez de\n"
	.string "points EXP., il monte de niveau.\p"
	.string "En changeant de niveau, les\n"
	.string "POKéMON deviennent plus forts.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POTE POKéMON: Oh, mon POKéMON\n"
	.string "a été empoisonné…\p"
	.string "Si un POKéMON est empoisonné,\n"
	.string "il perd ses PV progressivement.$"

Pokedude_Text_HealStatusRightAway::
	.string "Si un de tes POKéMON a un\n"
	.string "problème de statut, il faut le\p"
	.string "soigner le plus rapidement\n"
	.string "possible!$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Mais utiliser un objet sur un\n"
	.string "POKéMON compte comme un tour.\p"
	.string "C'est au tour de l'adversaire de\n"
	.string "jouer.$"

Pokedude_Text_YayWeManagedToWin::
	.string "Ouais!\n"
	.string "On a gagné!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POTE POKéMON: ECUME est une\n"
	.string "capacité de type EAU.\p"
	.string "La cible, MYSTHERBE, est un\n"
	.string "POKéMON de type PLANTE/POISON.\p"
	.string "L'attaque EAU est absorbée par le\n"
	.string "POKéMON PLANTE…\p"
	.string "Résultat, l'attaque perd de son\n"
	.string "efficacité et inflige moins de\p"
	.string "dégâts à l'adversaire.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Oh oh, c'est mauvais!\p"
	.string "L'attaque VOL-VIE que tu viens de\n"
	.string "voir est du type PLANTE.\p"
	.string "PTITARD est du type EAU.\p"
	.string "VOL-VIE est donc super efficace,\n"
	.string "et ses dégâts sont doublés.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Tu auras du mal à gagner à cause\n"
	.string "du rapport entre ces types.$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Changer de POKéMON pendant un\n"
	.string "combat coûte un tour.\p"
	.string "C'est à l'adversaire de jouer\n"
	.string "maintenant.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "PAPILUSION est un POKéMON de\n"
	.string "type INSECTE/VOL.\p"
	.string "Contre ce POKéMON, une attaque\n"
	.string "de type PLANTE…\p"
	.string "… inflige seulement la moitié\n"
	.string "des dégâts habituels sur\p"
	.string "un POKéMON de type INSECTE…\p"
	.string "… Et ses dégâts sont également\n"
	.string "réduits sur un POKéMON VOL.\p"
	.string "Pour cette raison, PAPILUSION\n"
	.string "étant un POKéMON INSECTE/VOL,\p"
	.string "il ne reçoit que le quart des\n"
	.string "dégâts habituels.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "MYSTHERBE est un POKéMON de\n"
	.string "type PLANTE/POISON.\p"
	.string "Une attaque de type VOL ou PSY\n"
	.string "est super efficace contre lui.\p"
	.string "Une attaque de ces types inflige\n"
	.string "le double de dégâts.\p"
	.string "Allez, on y va!$"

Pokedude_Text_YeahWeWon::
	.string "Ouais!\n"
	.string "On a gagné!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POTE POKéMON: Ne lance pas tes\n"
	.string "POKé BALLS immédiatement quand\p"
	.string "tu essaies d'attraper un POKéMON.\p"
	.string "Il faut d'abord l'affaiblir en\n"
	.string "diminuant ses PV.$"

Pokedude_Text_BestIfTargetStatused::
	.string "OK, ça devrait suffire.\p"
	.string "Mais ça serait encore mieux si la\n"
	.string "cible avait un problème de statut.\p"
	.string "Par exemple, il serait plus facile\n"
	.string "à attraper s'il était endormi\p"
	.string "ou paralysé.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "Avec ça, le POKéMON sera bien\n"
	.string "plus facile à attraper!\p"
	.string "Mais si tu paralyses un POKéMON, \n"
	.string "tu ne peux pas en plus l'endormir.\p"
	.string "En résumé, tu ne peux pas doubler\n"
	.string "les problèmes de statut, compris?$"

Pokedude_Text_LetMeThrowBall::
	.string "OK, laisse-moi lancer une\n"
	.string "POKé BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Avant de lancer une POKé BALL,\n"
	.string "pense à la condition et au type du\l"
	.string "POKéMON pour choisir la BALL\l"
	.string "la plus efficace.$"
