Text_OnlySkilledTrainersAllowedThrough::
	.string "Seul un DRESSEUR expérimenté\n"
	.string "peut passer.\p"
	.string "Tu n'as pas le {STR_VAR_1}!$"

Text_CantLetYouPass::
	.string "La loi est dure, mais c'est la loi!\n"
	.string "Tu ne peux pas passer.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! Tu as le {STR_VAR_1}!\n"
	.string "Tu peux passer!$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "On ne passe que sur présentation\n"
	.string "d'un {STR_VAR_1}.\p"
	.string "Tu n'as pas le {STR_VAR_1}.\p"
	.string "Il te le faut pour accéder à la\n"
	.string "LIGUE POKéMON!$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "On ne passe que sur présentation\n"
	.string "d'un {STR_VAR_1}!\p"
	.string "Oh! Mais c'est le {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "OK!\n"
	.string "Tu peux passer!$"
