@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\nBien sûr…$"

PalletTown_Text_OhLookLook::
	.string "Oh!\nRegarde, regarde!$"

PalletTown_Text_ReadItReadIt::
	.string "Lis-ça!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "ASTUCE\pSTART pour ouvrir le menu.$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Les panneaux sont utiles, hein?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Regarde, regarde!\p"
	.string "J'ai copié ce qui était écrit sur\n"
	.string "un des panneaux d'ASTUCES.$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "ASTUCE\p"
	.string "START pour ouvrir le menu.$"
