VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "La batterie n'est pas assez\n"
	.string "chargée.\p"
	.string "Il faut faire {STR_VAR_1} pas pour\n"
	.string "la recharger complètement.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Il n'y a pas de DRESSEUR aux\n"
	.string "alentours pour combattre.\p"
	.string "Le CHERCHE VS s'est éteint.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Les autres DRESSEURS ne sont\n"
	.string "pas prêts à se battre.\p"
	.string "Il va falloir patienter un peu.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Hé! On s'est déjà vu dans la FORET\n"
	.string "DE JADE!$"

Route3_Text_BenRematchIntro::
	.string "Yahaa!\p"
	.string "J'adore trop les shorts!\n"
	.string "Viens t'battre!$"

Route3_Text_JaniceRematchIntro::
	.string "Excuse-moi!\n"
	.string "Tu me cherches ou quoi?$"

Route3_Text_GregRematchIntro::
	.string "T'es un DRESSEUR toi, hein?\n"
	.string "A l'attaque!$"

Route3_Text_SallyRematchIntro::
	.string "Dis donc toi…\n"
	.string "Tu veux qu'on s'boxe?$"

Route3_Text_CalvinRematchIntro::
	.string "Hé! T'as pas de short!\n"
	.string "T'es vraiment naze!$"

Route3_Text_JamesRematchIntro::
	.string "Je vais te combattre avec les\n"
	.string "POKéMON que j'ai commencé\l"
	.string "à dresser.$"

Route3_Text_RobinRematchIntro::
	.string "Quoi?\n"
	.string "Qu'est-ce que tu me veux?$"

Route4_Text_CrissyRematchIntro::
	.string "J'attrape toujours des POKéMON\n"
	.string "champignon au MONT SELENITE.$"

Route6_Text_RickyRematchIntro::
	.string "Oh! C'est toi qui arrête pas de\n"
	.string "nous espionner, hein?$"

Route6_Text_NancyRematchIntro::
	.string "Excuse-moi!\p"
	.string "Tu vois pas que c'est une\n"
	.string "conversation privée?$"

Route6_Text_KeigoRematchIntro::
	.string "J'essaie de trouver autre chose\n"
	.string "que des POKéMON INSECTE, mais…$"

Route6_Text_JeffRematchIntro::
	.string "Hein?\n"
	.string "Tu veux encore te battre?$"

Route6_Text_IsabelleRematchIntro::
	.string "Qui ça? Moi?\n"
	.string "OK. Tu vas voir!$"

Route6_Text_ElijahRematchIntro::
	.string "Hé, ça faisait longtemps, hein?\p"
	.string "Tu vas voir le résultat de mon\n"
	.string "entraînement.$"

Route8_Text_AidanRematchIntro::
	.string "Tu maîtrises bien tes POKéMON.\n"
	.string "Mais tu bosses tes maths?$"

Route8_Text_StanRematchIntro::
	.string "Une fois encore, le sort en\n"
	.string "est jeté!$"

Route8_Text_GlennRematchIntro::
	.string "Il te faut une bonne stratégie!\n"
	.string "Tu devrais suivre mes conseils.$"

Route8_Text_PaigeRematchIntro::
	.string "J'ai attrapé beaucoup de NIDORAN.\n"
	.string "J'veux pas qu'ils évoluent, mais…$"

Route8_Text_LeslieRematchIntro::
	.string "L'école c'est cool, mais je pense\n"
	.string "toujours que les POKéMON\l"
	.string "c'est mieux!$"

Route8_Text_AndreaRematchIntro::
	.string "MIAOUSS et PERSIAN sont \n"
	.string "si mignons. Miaou!$"

Route8_Text_MeganRematchIntro::
	.string "J'ai l'air idiote à rester debout\n"
	.string "comme ça, mais je peux\p"
	.string "encore me battre.$"

Route8_Text_RichRematchIntro::
	.string "Je suis un joueur errant! Et je\n"
	.string "suis sur la route de la victoire.$"

Route8_Text_JuliaRematchIntro::
	.string "Qu'il est mimi, gentil et trognon ce\n"
	.string "POKéMON! Il est à qui?\l"
	.string "Hein? A qui?\p"
	.string "Tu le sais toujours pas?$"

Route8_Text_RicardoRematchIntro::
	.string "Toujours fidèle à ma bécane,\n"
	.string "ouais!$"

Route8_Text_JarenRematchIntro::
	.string "OK, ne t'attends pas à ce que je\n"
	.string "retienne mes coups.$"

Route8_Text_EliRematchIntro::
	.string "ELI: On est encore plus fortes\n"
	.string "qu'avant! Tu vas voir!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Plus rien ne peut nous\n"
	.string "résister!$"

Route9_Text_AliciaRematchIntro::
	.string "Le destin voulait qu'on se\n"
	.string "retrouve. Prépare-toi à perdre!$"

Route9_Text_ChrisRematchIntro::
	.string "T'as toujours les mêmes POKéMON?$"

Route9_Text_DrewRematchIntro::
	.string "Je passe par la GROTTE pour\n"
	.string "aller à LAVANVILLE.\p"
	.string "Mais j'arrête pas de rencontrer du\n"
	.string "monde en chemin.$"

Route9_Text_CaitlinRematchIntro::
	.string "Ne prends pas ce ton avec moi!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha! Allez…\n"
	.string "Je m'ennuyais, ça tombe bien…$"

Route9_Text_BriceRematchIntro::
	.string "T'as du cran toi!$"

Route9_Text_BrentRematchIntro::
	.string "Je me réveille de bonne heure tous\n"
	.string "les matins pour l'entraînement\p"
	.string "depuis notre dernière rencontre.\n"
	.string "Prépare-toi!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Cette fois, je gagnerai!$"

Route9_Text_ConnerRematchIntro::
	.string "En avant! Allez-y mes\n"
	.string "POKéMON INSECTE!$"

Route10_Text_MarkRematchIntro::
	.string "T'es dingue des POKéMON?\n"
	.string "Tu veux voir ma collection?$"

Route10_Text_ClarkRematchIntro::
	.string "Snnnf, j'arrête pas d'éternuer!\n"
	.string "J'ai dû attraper froid!$"

Route10_Text_HermanRematchIntro::
	.string "Hé, toi!\n"
	.string "Tu veux voir mes POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "Je suis retournée dans une ARENE.\n"
	.string "Mais j'ai encore perdu…$"

Route10_Text_TrentRematchIntro::
	.string "Ah! L'air de la montagne!\p"
	.string "C'est si bon que je peux\n"
	.string "pas partir!$"

Route10_Text_CarolRematchIntro::
	.string "J'ai la tête qui tourne.\n"
	.string "J'devrais vraiment me reposer…$"

Route11_Text_HugoRematchIntro::
	.string "Tu veux gagner ou perdre?$"

Route11_Text_JasperRematchIntro::
	.string "J'adore les défis!$"

Route11_Text_EddieRematchIntro::
	.string "On y va?\n"
	.string "OK, mais triche pas!$"

Route11_Text_BraxtonRematchIntro::
	.string "Attention!\n"
	.string "Je pose encore des câbles!$"

Route11_Text_DillonRematchIntro::
	.string "Ça fait un bout de temps que\n"
	.string "je suis DRESSEUR.\p"
	.string "Je vais gagner, tu vas voir.$"

Route11_Text_DirkRematchIntro::
	.string "HAHAHA!\n"
	.string "J'ai jamais perdu!\p"
	.string "Enfin, si je me souviens bien.$"

Route11_Text_DarianRematchIntro::
	.string "Je n'ai jamais gagné…\p"
	.string "Ça doit être mon destin.$"

Route11_Text_YasuRematchIntro::
	.string "Je suis le plus fort de ma classe!\n"
	.string "Je m'entraîne nuit et jour.$"

Route11_Text_BernieRematchIntro::
	.string "Fais gaffe aux câbles! Je te\n"
	.string "l'ai pourtant déjà dit.$"

Route11_Text_DaveRematchIntro::
	.string "Mes POKéMON sont prêts!\n"
	.string "Cette fois, on va gagner!$"

Route12_Text_NedRematchIntro::
	.string "Ça mord! Ça doit être une\n"
	.string "grosse prise!$"

Route12_Text_ChipRematchIntro::
	.string "Tu viens d'arriver?\n"
	.string "Pour pêcher, faut être patient!$"

Route12_Text_JustinRematchIntro::
	.string "Je cherche toujours une\n"
	.string "PIERRE LUNE.\p"
	.string "T'en as trouvé une?$"

Route12_Text_LucaRematchIntro::
	.string "L'électricité a toujours été\n"
	.string "ma spécialité!$"

Route12_Text_HankRematchIntro::
	.string "Le PECHEUR FOU contre le KID des\n"
	.string "POKéMON!\p"
	.string "Deuxième round!$"

Route12_Text_ElliotRematchIntro::
	.string "Bon, j'ai du pain sur la planche!$"

Route12_Text_AndrewRematchIntro::
	.string "Si, ça mord?\p"
	.string "Va falloir que tu me battes\n"
	.string "pour savoir!$"

Route12_Text_JesRematchIntro::
	.string "JES: Je gagnerai, et après,\n"
	.string "j'épouse GIA.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: JES! Tu sais depuis quand\n"
	.string "j'attends.\p"
	.string "Si on gagne, on se marie!$"

Route13_Text_SebastianRematchIntro::
	.string "Mes POKéMON oiseau se souviennent\n"
	.string "de toi!$"

Route13_Text_SusieRematchIntro::
	.string "Depuis tout petit, je veux devenir\n"
	.string "le meilleur DRESSEUR!$"

Route13_Text_ValerieRematchIntro::
	.string "Woaa!\n"
	.string "T'as encore plus de BADGES!$"

Route13_Text_GwenRematchIntro::
	.string "Mes POKéMON tout mignons veulent\n"
	.string "encore se battre.$"

Route13_Text_AlmaRematchIntro::
	.string "J'ai éclaté ma tirelire pour\n"
	.string "acheter plus de CARBONE.$"

Route13_Text_PerryRematchIntro::
	.string "Le vent souffle par là.\n"
	.string "Cool! J'perdrai pas cette fois!$"

Route13_Text_LolaRematchIntro::
	.string "Oh, de retour?\p"
	.string "Mais bien sûr que je veux bien\n"
	.string "qu'on s'affronte de nouveau.$"

Route13_Text_SheilaRematchIntro::
	.string "Comment oses-tu? Tu ne te souviens\n"
	.string "pas de ce joli visage?$"

Route13_Text_JaredRematchIntro::
	.string "Kess tu mates?$"

Route13_Text_RobertRematchIntro::
	.string "J'aime bien mes POKéMON oiseau!\n"
	.string "Ouais… Ça change pas.$"

Route14_Text_CarterRematchIntro::
	.string "J'ai utilisé des CT pour apprendre\n"
	.string "plein de capacités à mes POKéMON!$"

Route14_Text_MitchRematchIntro::
	.string "Mes POKéMON oiseau veulent\n"
	.string "se battre. Ils sont prêts.$"

Route14_Text_BeckRematchIntro::
	.string "Tu utilises des CT toi aussi? Ça\n"
	.string "sert à rien de juste les garder.$"

Route14_Text_MarlonRematchIntro::
	.string "As-tu appris à tes POKéMON oiseau\n"
	.string "à voler?$"

Route14_Text_DonaldRematchIntro::
	.string "La légende des mirages ailés…\n"
	.string "T'en as déjà entendu parler, hein?$"

Route14_Text_BennyRematchIntro::
	.string "J'suis pas au jeu!\n"
	.string "Mais bon…$"

Route14_Text_LukasRematchIntro::
	.string "Hé, j'me souviens de toi!\n"
	.string "Allez, viens!\p"
	.string "Tu vas voir la tête de tes\n"
	.string "POKéMON!$"

Route14_Text_IsaacRematchIntro::
	.string "Encore là?\n"
	.string "Tu vas déguster!$"

Route14_Text_GeraldRematchIntro::
	.string "On s'en va, y'a plus de place!$"

Route14_Text_MalikRematchIntro::
	.string "Combat POKéMON?\n"
	.string "Tremble, minus!$"

Route14_Text_KiriRematchIntro::
	.string "JOY: KATE, on va gagner, tu\n"
	.string "vas voir!$"

Route14_Text_JanRematchIntro::
	.string "KATE: Allez JOY, on y va!\n"
	.string "On peut pas perdre encore!$"

Route15_Text_KindraRematchIntro::
	.string "Je vais continuer à tester les\n"
	.string "POKéMON que j'ai échangés!$"

Route15_Text_BeckyRematchIntro::
	.string "Tu fais pas le poids, je devrais\n"
	.string "pouvoir te battre cette fois!$"

Route15_Text_EdwinRematchIntro::
	.string "Quand je sifflote, les POKéMON\n"
	.string "oiseau viennent autour de moi.\p"
	.string "C'est trop mignon.$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? Mes oiseaux ont peur!\n"
	.string "C'est toi qui leur fais peur?$"

Route15_Text_GraceRematchIntro::
	.string "Oh!\n"
	.string "T'es bien jeune toi!\p"
	.string "Mais…\n"
	.string "Je me souviens de toi!$"

Route15_Text_OliviaRematchIntro::
	.string "J'ai des POKéMON parce que je vis\n"
	.string "toute seule!\p"
	.string "Ça a pas changé.$"

Route15_Text_ErnestRematchIntro::
	.string "Oh, minus!\n"
	.string "Regarde ça!$"

Route15_Text_AlexRematchIntro::
	.string "Rends-moi la thune que tu\n"
	.string "me dois!$"

Route15_Text_CeliaRematchIntro::
	.string "Rien de plus cool que d'échanger\n"
	.string "des POKéMON!\p"
	.string "T'es pas d'accord?$"

Route15_Text_YazminRematchIntro::
	.string "Je veux me battre avec\n"
	.string "mes POKéMON! Encore!$"

Route15_Text_MyaRematchIntro::
	.string "MIA: Comme on se retrouve!\p"
	.string "Tu m'aides encore pour\n"
	.string "l'entraînement de mon frère?$"

Route15_Text_RonRematchIntro::
	.string "RON: Ma sœur est encore plus\n"
	.string "balèze qu'avant…$"

Route16_Text_LaoRematchIntro::
	.string "Kess t'as ta?$"

Route16_Text_KojiRematchIntro::
	.string "Joli vélo!\n"
	.string "Donne-le moi vite!$"

Route16_Text_LukeRematchIntro::
	.string "Viens t'battre!\n"
	.string "P'tit rat!$"

Route16_Text_HideoRematchIntro::
	.string "Hé!\n"
	.string "Ça fait deux fois là!$"

Route16_Text_CamronRematchIntro::
	.string "J'ai faim, j'suis furax et j'vais\n"
	.string "t'exploser!$"

Route16_Text_RubenRematchIntro::
	.string "BASTOONNNN!$"

Route16_Text_JedRematchIntro::
	.string "ALI: T'as déjà vu des amoureux\n"
	.string "comme nous? Moi, j'crois pas!$"

Route16_Text_LeaRematchIntro::
	.string "LISE: Parfois, je suis terrorisée\n"
	.string "par la force de notre amour.$"

Route17_Text_RaulRematchIntro::
	.string "Pff… Un gosse, ça a jamais\n"
	.string "de thunes!$"

Route17_Text_IsaiahRematchIntro::
	.string "Kess tu veux, toi l'mioche?$"

Route17_Text_VirgilRematchIntro::
	.string "Alors, on se balade?$"

Route17_Text_BillyRematchIntro::
	.string "On est des MOTARDS!\n"
	.string "Des vrais, des purs, des durs,\l"
	.string "des méchants… Si si!$"

Route17_Text_NikolasRematchIntro::
	.string "Tu sens pas l'orage venir?$"

Route17_Text_ZeekRematchIntro::
	.string "Mes POKéMON veulent pas évoluer.\n"
	.string "Ben pourquoi?$"

Route17_Text_JamalRematchIntro::
	.string "J'ai vraiment besoin d'un peu\n"
	.string "d'exercice!$"

Route17_Text_CoreyRematchIntro::
	.string "No future!$"

Route17_Text_JaxonRematchIntro::
	.string "Vraiment mignon ce VELO!\n"
	.string "Mais comment ça se conduit?$"

Route17_Text_WilliamRematchIntro::
	.string "Du vent gamin!\n"
	.string "J'suis épuisé!$"

Route18_Text_WiltonRematchIntro::
	.string "Je suis toujours à la recherche de\n"
	.string "POKéMON.\p"
	.string "Mais c'est vraiment pas facile.$"

Route18_Text_RamiroRematchIntro::
	.string "Cui cui cui!\n"
	.string "J'fais l'oiseau, tu reconnais?$"

Route18_Text_JacobRematchIntro::
	.string "T'es sur mon gazon, dégage!\p"
	.string "Je t'ai déjà dit que je voulais\n"
	.string "pas te voir.$"

Route19_Text_RichardRematchIntro::
	.string "On se baigne?$"

Route19_Text_ReeceRematchIntro::
	.string "Attends! Mouille-toi la nuque avant\n"
	.string "de plonger!$"

Route19_Text_MatthewRematchIntro::
	.string "J'aime nager!\p"
	.string "Toi, j'suis sûr que tu préfères\n"
	.string "le SURF, non?$"

Route19_Text_DouglasRematchIntro::
	.string "D'où vient le vent?\n"
	.string "Tu sais pas?$"

Route19_Text_DavidRematchIntro::
	.string "Je cherche toujours des\n"
	.string "POKéMON dans les grands fonds!$"

Route19_Text_TonyRematchIntro::
	.string "La mer, l'écume, les vagues…\n"
	.string "C'est beau!!!\p"
	.string "Et ça fait oublier les défaites.$"

Route19_Text_AnyaRematchIntro::
	.string "J'adorerais nager avec tes\n"
	.string "POKéMON.\p"
	.string "Tu m'en donnes un si je gagne?$"

Route19_Text_AliceRematchIntro::
	.string "Nager c'est cool!\n"
	.string "Faut juste penser à pas couler!$"

Route19_Text_AxleRematchIntro::
	.string "Ces eaux sont très dangereuses.\n"
	.string "Tu devrais pas être là!$"

Route19_Text_ConnieRematchIntro::
	.string "J'ai nagé jusque-là avec mes amis.\n"
	.string "C'est trop crevant…\p"
	.string "Tu tiens vraiment à ce qu'on\n"
	.string "se batte encore?$"

Route19_Text_LiaRematchIntro::
	.string "VIVI: T'es au courant? Mon frère\n"
	.string "est un vrai DRESSEUR!\p"
	.string "Mais il a encore besoin\n"
	.string "d'entraînement!$"

Route19_Text_LucRematchIntro::
	.string "SAM: C'est ma sœur qui m'a\n"
	.string "tout appris.$"

Route20_Text_BarryRematchIntro::
	.string "La mer est peu profonde ici,\n"
	.string "n'est-ce pas?$"

Route20_Text_ShirleyRematchIntro::
	.string "Je suis en vacances ici.\n"
	.string "T'es pas dèg?$"

Route20_Text_TiffanyRematchIntro::
	.string "J'aime faire la planche avec les\n"
	.string "poissons!$"

Route20_Text_IreneRematchIntro::
	.string "Et toi, qu'est-ce que tu fais pour\n"
	.string "les vacances?$"

Route20_Text_DeanRematchIntro::
	.string "Mate un peu mon corps de rêve!\p"
	.string "Il est encore plus parfait\n"
	.string "qu'avant.$"

Route20_Text_DarrinRematchIntro::
	.string "Tu fais quoi sur ce POKéMON?\n"
	.string "Tu sais pas nager?$"

Route20_Text_RogerRematchIntro::
	.string "Mes POKéMON oiseau m'ont\n"
	.string "déposé ici!$"

Route20_Text_NoraRematchIntro::
	.string "Mon frère m'a offert des perles.\n"
	.string "Et t'sais quoi? Elles ont grossi!$"

Route20_Text_MissyRematchIntro::
	.string "J'ai nagé depuis CRAMOIS'ILE!\n"
	.string "Comme je te le dis!$"

Route20_Text_MelissaRematchIntro::
	.string "Il y a un LABO POKéMON à\n"
	.string "CRAMOIS'ILE.\p"
	.string "Mon papa y travaille.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Tu veux savoir s'il y a des\n"
	.string "poissons ici?$"

Route21_North_Text_WadeRematchIntro::
	.string "J'ai eu une belle prise.\n"
	.string "Tu veux voir?$"

Route21_North_Text_SpencerRematchIntro::
	.string "La mer me purifie le corps\n"
	.string "et l'esprit.$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro:: 
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "J'ai attrapé mes POKéMON\n"
	.string "dans l'océan.\p"
	.string "Et c'est là que je les entraîne.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Hop là!\n"
	.string "J'suis encore en plein triathlon!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ah! Le ciel, le soleil et la mer!\n"
	.string "… Ça craint.$"

Route21_South_Text_ClaudeRematchIntro::
	.string "J'le crois pas.\n"
	.string "Tu fais encore peur aux poissons.$"

Route21_South_Text_NolanRematchIntro::
	.string "Reste donc avec moi, le temps\n"
	.string "d'avoir une touche!$"

Route21_North_Text_LilRematchIntro::
	.string "LY: Un autre combat?\n"
	.string "IAN, t'en dis quoi?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: Ma sœur est une vraie\n"
	.string "feignasse!\p"
	.string "Tu m'aides à la secouer?$"

Route25_Text_JoeyRematchIntro::
	.string "Faudra me passer sur le corps.$"

Route25_Text_DanRematchIntro::
	.string "Je suis allé à une super fête\n"
	.string "avec mon père.\p"
	.string "C'était sur L'OCEANE, à\n"
	.string "CARMIN SUR MER!$"

Route25_Text_FlintRematchIntro::
	.string "J'suis cool.\n"
	.string "Et j'ai une copine aussi!\p"
	.string "Cette fois, elle va vraiment voir\n"
	.string "comme je suis cool.$"

Route25_Text_KelseyRematchIntro::
	.string "Mon p'tit copain, c'est le plus beau\n"
	.string "de tous! J'ai le plus beau de tous\l"
	.string "les copains du monde!$"

Route25_Text_ChadRematchIntro::
	.string "Y'a comme qui dirait un DRESSEUR\n"
	.string "de trop ici!$"

Route25_Text_HaleyRematchIntro::
	.string "Mon copain a des POKéMON trognons!\n"
	.string "Je suis jalouse!$"

Route25_Text_FranklinRematchIntro::
	.string "Je viens du MONT SELENITE, mais\n"
	.string "j'ai encore la force de me battre!$"

Route25_Text_NobRematchIntro::
	.string "Je cherche le collectionneur de\n"
	.string "POKéMON!$"

Route25_Text_WayneRematchIntro::
	.string "Tu cherches encore LEO?\n"
	.string "Ok, mais d'abord, BASTOONNN!$"

Route24_Text_ShaneRematchIntro::
	.string "J'ai suivi tes traces de pas\n"
	.string "dans l'herbe!$"

Route24_Text_EthanRematchIntro::
	.string "OK!\n"
	.string "J'vais te broyer!$"

Route24_Text_ReliRematchIntro::
	.string "Tu fais rien là?\n"
	.string "Un petit combat?$"

Route24_Text_TimmyRematchIntro::
	.string "T'aimes la vue?$"

Route24_Text_AliRematchIntro::
	.string "La dernière fois…\p"
	.string "J'ai perdu mais je suis sûre que\n"
	.string "c'était un manque de pot!$"

Route24_Text_CaleRematchIntro::
	.string "C'est le PONT PEPITE!\p"
	.string "Tu nous as déjà vus. Alors tu peux\n"
	.string "pas relever le défi…\p"
	.string "Mais par contre, j'ai rien contre\n"
	.string "un petit combat.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Bercée par les vagues, je vois\n"
	.string "même plus le temps passer.$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Le temps est super! Je vais pas\n"
	.string "te laisser gâcher cette journée.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "J'aurais dû faire attention aux\n"
	.string "coups de soleil.$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "La montagne de l'oiseau de feu\n"
	.string "fait de l'ombre.$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "J'ai l'impression que je vais\n"
	.string "gagner cette fois.$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Attends, attends un peu!\n"
	.string "J'ai une belle prise là!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Un petit match pour pas perdre\n"
	.string "la main?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "On a pas manqué un seul jour\n"
	.string "d'entraînement!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Tous les jours avant le p'tit déj,\n"
	.string "je fais le tour de l'île à la nage…\p"
	.string "Trois fois!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Habille-toi un peu mieux pour\n"
	.string "combattre! C'est quoi cette tenue?$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Tout semble différent quand on\n"
	.string "est seul en pleine nature.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "J'ai mangé trop de saucisses,\n"
	.string "il me faudrait un peu d'exercice.$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Mon frère et moi, on fait\n"
	.string "vraiment la paire!\p"
	.string "On peut pas perdre…\n"
	.string "Cette fois…$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: On a vraiment peur de rien!\n"
	.string "Mais frappe pas trop fort…$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "On se bat encore?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Mais dis-moi, tu vas où\n"
	.string "comme ça?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Dans pas longtemps, je nagerai\n"
	.string "sans ma bouée. Si, si…$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Allez mes POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Combien de fois je dois le répéter.\n"
	.string "Ne t'approche pas!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "BEA: On est encore plus balèzes.\n"
	.string "Beaucoup plus!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "EVA: Tu pourras jamais gagner!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Salut!\p"
	.string "Tu prends bien soin de tes\n"
	.string "POKéMON, j'espère.$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Ces mains m'apporteront\n"
	.string "la victoire!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Je dois le répéter?\p"
	.string "J'essaie de peindre. Alors,\n"
	.string "hors de ma vue!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Aucun progrès…\n"
	.string "Impossible d'avoir le bon angle…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Tu vas me donner la chance de\n"
	.string "me mesurer à toi?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "La piscine pour mes POKéMON\n"
	.string "est presque prête.\p"
	.string "Faudra passer la voir à l'occasion.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Je suis un bon sprinter. Et j'ai\n"
	.string "encore progressé.$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Dis, on se fait un petit combat\n"
	.string "pour passer le temps?$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Je suis l'aîné des FRERES PIAF.\n"
	.string "Tu te souviens?\p"
	.string "C'est ça, c'est moi qui aime\n"
	.string "les coups de bec!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Le cadet des FRERES PIAF,\n"
	.string "c'est moi!\p"
	.string "Moi mon truc, c'est les ailes.\n"
	.string "Un petit combat?$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Je suis le plus jeune des\n"
	.string "FRERES PIAF.\p"
	.string "Je pensais pas qu'on se reverrait.$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Toujours rien. Il me faudrait une\n"
	.string "petite victoire pour changer.$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Pfffff…\p"
	.string "J'arrive du port de l'ILE 6 à la\n"
	.string "nage. J'en peux… plus…$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Faut toujours que tu te pointes\n"
	.string "quand je nage.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Je ferais bien un petit\n"
	.string "deux contre deux! OK?$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GED: Avec ma sœur, on a\n"
	.string "peur de rien.$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "… Hein?\p"
	.string "Je voulais aller chez moi, mais le\n"
	.string "TELEPORT m'a amenée ici!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Tiens, bonjour.\n"
	.string "Sens-tu la brise se lever?$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, je m'entraîne toujours\n"
	.string "en secret.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Quoi? T'en as assez de voir des\n"
	.string "NAGEURS comme moi?\p"
	.string "Bah alors faut pas te baigner!$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Snnnf…\n"
	.string "Mon copain est encore occupé.$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Allez, tu veux pas me dire où\n"
	.string "sont les montagnes?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Salut les POKéMON!\n"
	.string "C'est le moment de se battre!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Petits POKéMON…\n"
	.string "On se fait un petit combat?$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Il y a toujours des mystères\n"
	.string "inexpliqués dans ce monde.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Tiens, on se connaît, non?\n"
	.string "Pourquoi t'es de retour?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Il paraît qu'il y a des pierres\n"
	.string "mystérieuses sur l'île.\p"
	.string "Tu me tiens au courant si tu\n"
	.string "découvres un truc, OK?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Une revanche?\n"
	.string "Allez, c'est parti!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Je connais bien la région, je\n"
	.string "peux pas perdre.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "J'ai senti que tu venais.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Quelque part sur cette île, un\n"
	.string "POKéMON spécial se repose.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Hi hi hi!\p"
	.string "Je vais me débarrasser de toi\n"
	.string "sans efforts.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "YO! T'es membre de mon fan club?\n"
	.string "C'est pour ça que t'es là?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Cette île est trop vaste… Il\n"
	.string "faut des heures pour patrouiller…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Je ne pardonne pas à ceux qui\n"
	.string "maltraitent les POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Avec JOE, on te laissera\n"
	.string "aucune chance!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JOE: Avec EVE, j'ai l'impression\n"
	.string "d'être invincible.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Faisons un combat. Je suis au\n"
	.string "top de ma forme!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Peu importe que tu aies les\n"
	.string "POKéMON les plus forts…\p"
	.string "Ça ne sert à rien si tu ne sais pas\n"
	.string "les utiliser correctement!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Je travaille pour protéger\n"
	.string "l'environnement.\p"
	.string "Et toi, tu fais quoi pour protéger\n"
	.string "la nature?$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "T'as toujours cette pauvre paire\n"
	.string "de chaussures?$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Tu dois être plus coriace, non?\n"
	.string "Allez, montre-moi!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "J'ai reçu la meilleure éducation\n"
	.string "pour être aussi forte.\p"
	.string "Je ne peux pas perdre cette fois!\n"
	.string "Oh que non!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "PAUL: Ma chère NYA, la victoire\n"
	.string "est à nous!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: Je ne laisserai jamais tomber\n"
	.string "mon mentor. PAUL, on va gagner!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "As-tu découvert quelque chose\n"
	.string "sur cette grotte?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "On raconte qu'un POKéMON\n"
	.string "mystique dort ici.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Mon prof m'apprend comment\n"
	.string "mieux peindre.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Aujourd'hui, en plus des leçons,\n"
	.string "nous sommes revenus voir la grotte.$"

