Text_FirstShouldRestoreMonsHealth::
	.string "Avant toute chose, vous devriez\n"
	.string "faire soigner vos POKéMON.$"

Text_MonsHealedShouldBuyPotions::
	.string "Vos POKéMON ont été soignés.\p"
	.string "Si les PV de vos POKéMON sont\n"
	.string "faibles, venez nous voir.\p"
	.string "Si vous prévoyez de partir loin,\p"
	.string "vous devriez acheter des POTIONS\n"
	.string "dans une BOUTIQUE POKéMON.\p"
	.string "Nous vous souhaitons\n"
	.string "bonne chance.$"

Text_MonsHealed::
	.string "Vos POKéMON ont été soignés.\p"
	.string "Nous vous souhaitons\n"
	.string "bonne chance.$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MAMAN: Comment ça va, \n"
	.string "{PLAYER}?\p"
	.string "Tu as dû vivre des aventures\n"
	.string "épuisantes.\p"
	.string "Tu devrais faire une sieste.$"

Text_MomExplainHPGetPotions::
	.string "MAMAN: Eh bien, toi et tes\n"
	.string "POKéMON avez l'air d'aller mieux.\p"
	.string "Je viens d'avoir des nouvelles\n"
	.string "du PROF. CHEN.\p"
	.string "Il dit que l'énergie d'un POKéMON\n"
	.string "se mesure en PV.\p"
	.string "Si tes POKéMON manquent de\n"
	.string "PV, tu peux les restaurer en allant\p"
	.string "dans un centre POKéMON. Et si\n"
	.string "tu prévois de voyager loin,\p"
	.string "n'oublie pas d'acheter des POTIONS\n"
	.string "dans une BOUTIQUE POKéMON.\p"
	.string "Rends-moi fière, mon bouchon.\n"
	.string "Fais attention à toi!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} n'a plus de POKéMON!\p"
	.string "{PLAYER} panique et perd {STR_VAR_1}¥…\p"
	.string "… … … …\p"
	.string "{PLAYER} est hors-jeu!$"

Text_WhitedOut::
	.string "{PLAYER} n'a plus de POKéMON!\p"
	.string "{PLAYER} est hors-jeu!$"
