
@ Unused, from R/S
Text_DoorOpenedFarAway::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments::
	.string "Je suis vraiment désolée.\p"
	.string "Le CLUB SANS FIL POKéMON\n"
	.string "est encore en préparation.$"

Text_AppearsToBeUndergoingAdjustments::
	.string "Ils sont en train d'effectuer\n"
	.string "des réglages…$"

Text_HandedOverItem::
	.string "{PLAYER} remet {STR_VAR_1}.$"

Text_GiveNicknameToThisMon::
	.string "Voulez-vous donner un surnom\n"
	.string "à {STR_VAR_1}?$"
