#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] =  _("Ecrase l'ennemi\navec les pattes\navant ou la queue.");
const u8 gMoveDescription_KarateChop[] =  _("Une attaque\ntranchante à taux\nde critiques élevé.");
const u8 gMoveDescription_DoubleSlap[] =  _("Gifle rapidement\nl'ennemi\nde 2 à 5 fois.");
const u8 gMoveDescription_CometPunch[] =  _("Frappe rapidement\nl'ennemi\nde 2 à 5 fois.");
const u8 gMoveDescription_MegaPunch[] =  _("Un coup de poing\nd'une puissance\nincroyable.");
const u8 gMoveDescription_PayDay[] =  _("Lance des pièces.\nL'argent est\nrécupéré plus tard.");
const u8 gMoveDescription_FirePunch[] =  _("Un poing de feu\npouvant brûler\nl'ennemi.");
const u8 gMoveDescription_IcePunch[] =  _("Un poing de glace\npouvant\ngeler l'ennemi.");
const u8 gMoveDescription_ThunderPunch[] =  _("Un poing électrique\npouvant paralyser\nl'ennemi.");
const u8 gMoveDescription_Scratch[] =  _("Lacère l'ennemi\navec des griffes\nacérées.");
const u8 gMoveDescription_ViceGrip[] =  _("Empoigne l'ennemi\navec de puissantes\npinces.");
const u8 gMoveDescription_Guillotine[] =  _("Un puissant coup\nde pince qui peut\nmettre KO.");
const u8 gMoveDescription_RazorWind[] =  _("Une attaque en\n2 tours qui\nfrappe au\n2{SUPER_E} tour.");
const u8 gMoveDescription_SwordsDance[] =  _("Une danse de\ncombat pour\nbooster l'ATTAQUE.");
const u8 gMoveDescription_Cut[] =  _("Une attaque\nbasique. Peut \ncouper des\npetits arbres.");
const u8 gMoveDescription_Gust[] =  _("Envoie une rafale\nde vent en battant\ndes ailes.");
const u8 gMoveDescription_WingAttack[] =  _("Frappe l'ennemi\nen déployant les\nailes.");
const u8 gMoveDescription_Whirlwind[] =  _("Envoie une rafale\nde vent et met fin\nau combat.");
const u8 gMoveDescription_Fly[] =  _("S'envole au premier\ntour et frappe au\nsecond.");
const u8 gMoveDescription_Bind[] =  _("Ligote l'ennemi et\nl'écrase pendant\n2 à 5 tours.");
const u8 gMoveDescription_Slam[] =  _("Fouette l'ennemi\navec la queue, une\nliane, etc.");
const u8 gMoveDescription_VineWhip[] =  _("Fouette l'ennemi\navec de fines\nlianes.");
const u8 gMoveDescription_Stomp[] =  _("Ecrase avec un\nénorme pied. Peut\napeurer l'ennemi.");
const u8 gMoveDescription_DoubleKick[] =  _("Un double coup de\npied qui frappe\nl'ennemi deux fois.");
const u8 gMoveDescription_MegaKick[] =  _("Un coup de pied\nsuper puissant\net intense.");
const u8 gMoveDescription_JumpKick[] =  _("Un coup de pied\nsauté. Peut blesser\nle lanceur si raté.");
const u8 gMoveDescription_RollingKick[] =  _("Un coup de pied\ntournoyant et\nextrêmement rapide.");
const u8 gMoveDescription_SandAttack[] =  _("Lance du sable et\nbaisse la précision\nde l'ennemi.");
const u8 gMoveDescription_Headbutt[] =  _("Une charge qui\npeut apeurer\nl'ennemi.");
const u8 gMoveDescription_HornAttack[] =  _("Frappe l'ennemi\nd'un coup\nde corne pointue.");
const u8 gMoveDescription_FuryAttack[] =  _("Frappe l'ennemi\n2 à 5 fois avec\nune corne, un bec,\netc.");
const u8 gMoveDescription_HornDrill[] =  _("Empale l'ennemi\nd'un coup de corne.\nMet KO en un coup.");
const u8 gMoveDescription_Tackle[] =  _("Charge l'ennemi\navec un\nviolent plaquage.");
const u8 gMoveDescription_BodySlam[] =  _("Une attaque en\ncharge. Peut\nparalyser l'ennemi.");
const u8 gMoveDescription_Wrap[] =  _("Ligote l'ennemi et\nl'étouffe pendant\n2 à 5 tours avec\ndes lianes.");
const u8 gMoveDescription_TakeDown[] =  _("Une charge violente\nqui blesse aussi\nlégèrement le\nlanceur.");
const u8 gMoveDescription_Thrash[] =  _("Une attaque\nfurieuse de 2 à 3\ntours. Le lanceur\ndevient confus.");
const u8 gMoveDescription_DoubleEdge[] =  _("Une dangereuse\ncharge qui blesse\naussi légèrement\nle lanceur.");
const u8 gMoveDescription_TailWhip[] =  _("Remue la queue\npour baisser la\nDEFENSE de\nl'ennemi.");
const u8 gMoveDescription_PoisonSting[] =  _("Une attaque de\ndards, etc.,\npouvant\nempoisonner.");
const u8 gMoveDescription_Twineedle[] =  _("Les dards des\npattes avant\nfrappent\ndeux fois.");
const u8 gMoveDescription_PinMissile[] =  _("Envoie des dards\nqui frappent\n2 à 5 fois.");
const u8 gMoveDescription_Leer[] =  _("Lance un regard\nnoir et baisse\nla DEFENSE.");
const u8 gMoveDescription_Bite[] =  _("Mord méchamment\nl'ennemi et peut\nl'apeurer.");
const u8 gMoveDescription_Growl[] =  _("Rugit gentiment\net baisse\nl'ATTAQUE de\nl'ennemi.");
const u8 gMoveDescription_Roar[] =  _("Fait fuir l'ennemi\npour mettre fin au\ncombat.");
const u8 gMoveDescription_Sing[] =  _("Berceuse plongeant\nl'ennemi dans un\nprofond sommeil.");
const u8 gMoveDescription_Supersonic[] =  _("Etranges ondes\nsonores pouvant\nrendre confus.");
const u8 gMoveDescription_SonicBoom[] =  _("Envoie des ondes\nde choc infligeant\n20 PV de dégâts.");
const u8 gMoveDescription_Disable[] =  _("Empêche\nl'utilisation d'une\ndes attaques\nde l'ennemi.");
const u8 gMoveDescription_Acid[] =  _("Pulvérise un acide.\nPeut baisser la\nDEFENSE ennemie.");
const u8 gMoveDescription_Ember[] =  _("Une faible attaque\nde feu pouvant\nbrûler l'ennemi.");
const u8 gMoveDescription_Flamethrower[] =  _("Une puissante\nattaque de feu\npouvant brûler\nl'ennemi.");
const u8 gMoveDescription_Mist[] =  _("Crée une brume\nstoppant la\nréduction\ndes capacités.");
const u8 gMoveDescription_WaterGun[] =  _("Attaque l'ennemi\nen projetant de\nl'eau.");
const u8 gMoveDescription_HydroPump[] =  _("Envoie un\npuissant jet\nd'eau pour\nfrapper l'ennemi.");
const u8 gMoveDescription_Surf[] =  _("Crée une énorme\nvague qui\ns'écrase sur\nl'ennemi.");
const u8 gMoveDescription_IceBeam[] =  _("Envoie un rayon\nde glace\npouvant geler\nl'ennemi.");
const u8 gMoveDescription_Blizzard[] =  _("Déclenche une\ntempête de neige\npouvant geler\nl'ennemi.");
const u8 gMoveDescription_Psybeam[] =  _("Etrange rayon\npouvant rendre\nl'ennemi confus.");
const u8 gMoveDescription_BubbleBeam[] =  _("Envoie des bulles\npouvant baisser\nla VITESSE.");
const u8 gMoveDescription_AuroraBeam[] =  _("Envoie un rayon\narc-en-ciel\npouvant baisser\nl'ATTAQUE.");
const u8 gMoveDescription_HyperBeam[] =  _("Puissant, mais \nimmobilise\nle lanceur pour\nun tour.");
const u8 gMoveDescription_Peck[] =  _("Attaque l'ennemi\navec une corne,\nun bec pointu, etc.");
const u8 gMoveDescription_DrillPeck[] =  _("Une attaque\nutilisant le\nbec comme\nune perceuse.");
const u8 gMoveDescription_Submission[] =  _("Une charge\nviolente qui\nblesse aussi\nle lanceur.");
const u8 gMoveDescription_LowKick[] =  _("Un coup de pied\nfaisant plus de\ndégâts aux ennemis\nlourds.");
const u8 gMoveDescription_Counter[] =  _("Renvoie toute\nattaque physique,\n2 fois plus fort.");
const u8 gMoveDescription_SeismicToss[] =  _("Inflige des dégâts\nselon le niveau\ndu lanceur.");
const u8 gMoveDescription_Strength[] =  _("Accumule de la\npuissance,\npuis frappe\nl'ennemi.");
const u8 gMoveDescription_Absorb[] =  _("Une attaque\nqui convertit les\ndégâts infligés\nen PV.");
const u8 gMoveDescription_MegaDrain[] =  _("Une attaque qui\nconvertit la moitié\ndes dégâts infligés\nen PV.");
const u8 gMoveDescription_LeechSeed[] =  _("Plante des graines\npour voler des PV\nà chaque tour.");
const u8 gMoveDescription_Growth[] =  _("Développe le\ncorps et augmente\nl'ATQ. SPE.");
const u8 gMoveDescription_RazorLeaf[] =  _("Tranche avec\ndes feuilles.\nTaux de critiques\nélevé.");
const u8 gMoveDescription_SolarBeam[] =  _("Absorbe la lumière\net attaque le tour\nsuivant.");
const u8 gMoveDescription_PoisonPowder[] =  _("Répand une poudre\ntoxique pouvant\nempoisonner.");
const u8 gMoveDescription_StunSpore[] =  _("Répand une poudre\npouvant paralyser\nl'ennemi.");
const u8 gMoveDescription_SleepPowder[] =  _("Répand une poudre\npouvant endormir\nl'ennemi.");
const u8 gMoveDescription_PetalDance[] =  _("Une attaque\nfurieuse de 2 à 3\ntours. Le lanceur\ndevient confus.");
const u8 gMoveDescription_StringShot[] =  _("Ligote l'ennemi\nafin de réduire\nsa VITESSE.");
const u8 gMoveDescription_DragonRage[] =  _("Envoie des ondes\nde choc infligeant\n40 PV de dégâts.");
const u8 gMoveDescription_FireSpin[] =  _("Encercle l'ennemi\navec des flammes\npendant 2 à 5\ntours.");
const u8 gMoveDescription_ThunderShock[] =  _("Une attaque\nélectrique pouvant\nparalyser l'ennemi.");
const u8 gMoveDescription_Thunderbolt[] =  _("Une forte attaque\nélectrique pouvant\nparalyser l'ennemi.");
const u8 gMoveDescription_ThunderWave[] =  _("Un faible choc\nélectrique qui\nparalyse l'ennemi.");
const u8 gMoveDescription_Thunder[] =  _("Une attaque\nfoudroyante pouvant\nparalyser l'ennemi.");
const u8 gMoveDescription_RockThrow[] =  _("Envoie des cailloux\npour frapper\nl'ennemi.");
const u8 gMoveDescription_Earthquake[] =  _("Tremblement de\nterre sans effet\nsur les adversaires\nvolants.");
const u8 gMoveDescription_Fissure[] =  _("Fait tomber\nl'ennemi dans une\ncrevasse et le\nmet KO.");
const u8 gMoveDescription_Dig[] =  _("Creuse sous terre\nau 1{SUPER_ER} tour\net frappe au 2{SUPER_E}.");
const u8 gMoveDescription_Toxic[] =  _("Empoisonne\nl'ennemi avec\nune toxine de plus\nen plus forte.");
const u8 gMoveDescription_Confusion[] =  _("Une attaque PSY\npouvant rendre\nl'ennemi confus.");
const u8 gMoveDescription_Psychic[] =  _("Une puissante\nattaque PSY\npouvant baisser\nla DEF. SPE.");
const u8 gMoveDescription_Hypnosis[] =  _("Une attaque\nhypnotique\npouvant endormir\nl'ennemi.");
const u8 gMoveDescription_Meditate[] =  _("Méditation\npacifique pour\naugmenter\nl'ATTAQUE.");
const u8 gMoveDescription_Agility[] =  _("Relaxation du\ncorps pour\nbooster la\nVITESSE.");
const u8 gMoveDescription_QuickAttack[] =  _("Attaque fulgurante\nqui permet de\nfrapper en premier.");
const u8 gMoveDescription_Rage[] =  _("Augmente\nl'ATTAQUE du\nlanceur à chaque\ncoup reçu.");
const u8 gMoveDescription_Teleport[] =  _("Attaque PSY\npermettant de\nprendre aussitôt\nla fuite.");
const u8 gMoveDescription_NightShade[] =  _("Un mirage qui\ninflige des dégâts\nselon le niveau\ndu lanceur.");
const u8 gMoveDescription_Mimic[] =  _("Imite la\ndernière attaque\nutilisée par\nl'ennemi.");
const u8 gMoveDescription_Screech[] =  _("Cri strident qui\nbaisse beaucoup\nla DEFENSE\nennemie.");
const u8 gMoveDescription_DoubleTeam[] =  _("Crée des\nimages-miroirs\npour augmenter\nl'esquive.");
const u8 gMoveDescription_Recover[] =  _("Restaure jusqu'à\nla moitié des PV\nmax du lanceur.");
const u8 gMoveDescription_Harden[] =  _("Contracte les\nmuscles pour\naugmenter la\nDEFENSE.");
const u8 gMoveDescription_Minimize[] =  _("Rapetisse le\nlanceur pour\naugmenter\nl'esquive.");
const u8 gMoveDescription_Smokescreen[] =  _("Baisse la précision\nennemie en\nutilisant fumée,\nencre, etc.");
const u8 gMoveDescription_ConfuseRay[] =  _("Un horrible rayon\nqui rend\nl'ennemi confus.");
const u8 gMoveDescription_Withdraw[] =  _("Se recroqueville\ndans sa carapace\net augmente la\nDEFENSE.");
const u8 gMoveDescription_DefenseCurl[] =  _("S'enroule pour\ncacher ses points\nfaibles et monter\nsa DEFENSE.");
const u8 gMoveDescription_Barrier[] =  _("Crée une barrière\npour booster la\nDEFENSE.");
const u8 gMoveDescription_LightScreen[] =  _("Crée un mur\nlumineux et\nréduit les dégâts\nd'ATQ. SPE.");
const u8 gMoveDescription_Haze[] =  _("Crée un nuage noir\nannulant tout\nchangement d'état.");
const u8 gMoveDescription_Reflect[] =  _("Crée un mur\nlumineux qui\naffaiblit les att.\nphysiques 5 tours.");
const u8 gMoveDescription_FocusEnergy[] =  _("Concentration\npour booster\nle taux de\ncritiques.");
const u8 gMoveDescription_Bide[] =  _("Encaisse les\nattaques sur 2\ntours et renvoie\nle double.");
const u8 gMoveDescription_Metronome[] =  _("Remue un doigt\net lance une\nattaque POKéMON\nau hasard.");
const u8 gMoveDescription_MirrorMove[] =  _("Contre l'attaque de\nl'ennemi avec la\nmême attaque.");
const u8 gMoveDescription_SelfDestruct[] =  _("Inflige de sérieux\ndégâts, mais met le\nlanceur KO.");
const u8 gMoveDescription_EggBomb[] =  _("Envoie violemment\nun œuf en direction\nde l'ennemi.");
const u8 gMoveDescription_Lick[] =  _("Blesse avec un long\ncoup de langue.\nPeut paralyser.");
const u8 gMoveDescription_Smog[] =  _("Un gaz nocif\npouvant empoisonner\nl'ennemi.");
const u8 gMoveDescription_Sludge[] =  _("Blesse en envoyant\ndes détritus\ntoxiques. Peut\nempoisonner.");
const u8 gMoveDescription_BoneClub[] =  _("Cogne l'ennemi\navec un os. Peut\napeurer.");
const u8 gMoveDescription_FireBlast[] =  _("Une explosion\nde flammes.\nPeut brûler\nl'ennemi.");
const u8 gMoveDescription_Waterfall[] =  _("Charge puissante\npermettant de\nfranchir des\ncascades.");
const u8 gMoveDescription_Clamp[] =  _("Piège l'ennemi et\nl'écrase pendant\n2 à 5 tours.");
const u8 gMoveDescription_Swift[] =  _("Envoie des rayons\nen forme d'étoile.\nTouche toujours\nla cible.");
const u8 gMoveDescription_SkullBash[] =  _("Monte la DEFENSE\nau 1{SUPER_ER} tour\net frappe au 2{SUPER_E}.");
const u8 gMoveDescription_SpikeCannon[] =  _("Lance des pointes\nqui frappent\n2 à 5 fois.");
const u8 gMoveDescription_Constrict[] =  _("Etrangle avec des\ntentacules ou des\nlianes. Peut baisser\nla VITESSE.");
const u8 gMoveDescription_Amnesia[] =  _("Oublie quelque\nchose et\nbooste la\nDEF. SPE.");
const u8 gMoveDescription_Kinesis[] =  _("Distrait l'ennemi\navec une cuillère.\nPeut baisser la\nprécision.");
const u8 gMoveDescription_SoftBoiled[] =  _("Restaure jusqu'à\nla moitié des PV\nmax. Utilisable sur\nun allié.");
const u8 gMoveDescription_HiJumpKick[] =  _("Coup de pied\nsauté. S'il est\nraté, le lanceur\nse blesse.");
const u8 gMoveDescription_Glare[] =  _("Intimide l'ennemi\net le paralyse de\nterreur.");
const u8 gMoveDescription_DreamEater[] =  _("Convertit en PV la\nmoitié des dégâts\ninfligés à l'ennemi\nendormi.");
const u8 gMoveDescription_PoisonGas[] =  _("Enveloppe l'ennemi\nd'un gaz toxique.\nPeut empoisonner.");
const u8 gMoveDescription_Barrage[] =  _("Projette 2 à 5 fois\ndes objets ronds\nvers l'ennemi.");
const u8 gMoveDescription_LeechLife[] =  _("Une attaque qui\nconvertit en PV\nla moitié des\ndégâts infligés.");
const u8 gMoveDescription_LovelyKiss[] =  _("Demande un bisou\nen grimaçant.\nPeut endormir.");
const u8 gMoveDescription_SkyAttack[] =  _("Attaque en 2 tours.\nTaux de critiques\nélevé. Peut\napeurer l'ennemi.");
const u8 gMoveDescription_Transform[] =  _("Modifie ses\ncellules pour\ncopier l'ennemi.");
const u8 gMoveDescription_Bubble[] =  _("Une attaque de\nbulles pouvant\nbaisser la VITESSE.");
const u8 gMoveDescription_DizzyPunch[] =  _("Un coup de poing\ncadencé. Peut\nrendre confus.");
const u8 gMoveDescription_Spore[] =  _("Répand un nuage\nde spores qui\nendort.");
const u8 gMoveDescription_Flash[] =  _("Explosion lumineuse\nqui fait baisser\nla précision.");
const u8 gMoveDescription_Psywave[] =  _("Envoie une onde\nPSY d'intensité\nvariable.");
const u8 gMoveDescription_Splash[] =  _("Eclabousse l'ennemi\nsans aucun effet.");
const u8 gMoveDescription_AcidArmor[] =  _("Liquéfie le corps\ndu lanceur et\nbooste sa DEFENSE.");
const u8 gMoveDescription_Crabhammer[] =  _("Attaque critique\nqui utilise une\ngrosse pince.");
const u8 gMoveDescription_Explosion[] =  _("Inflige de sérieux\ndégâts, mais met le\nlanceur KO.");
const u8 gMoveDescription_FurySwipes[] =  _("Ecorche l'ennemi\navec des griffes\nou des faux\nde 2 à 5 fois.");
const u8 gMoveDescription_Bonemerang[] =  _("Lance un boomerang\nen os qui frappe\ndeux fois.");
const u8 gMoveDescription_Rest[] =  _("Le lanceur dort\n2 tours et regagne\nses PV et son\nstatut normal.");
const u8 gMoveDescription_RockSlide[] =  _("Envoie de gros\nrochers. Peut\napeurer l'ennemi.");
const u8 gMoveDescription_HyperFang[] =  _("Blesse d'un coup\nde croc. Peut\napeurer l'ennemi.");
const u8 gMoveDescription_Sharpen[] =  _("Réduit le nombre\nde polygones\net augmente\nl'ATTAQUE.");
const u8 gMoveDescription_Conversion[] =  _("Change le type\ndu lanceur en\ncelui d'une\ncapacité.");
const u8 gMoveDescription_TriAttack[] =  _("Envoie trois types\nde rayons en\nmême temps.");
const u8 gMoveDescription_SuperFang[] =  _("Coup de croc qui\nfait baisser les\nPV de moitié.");
const u8 gMoveDescription_Slash[] =  _("Coups de griffe,\netc. Taux de\ncritiques élevé.");
const u8 gMoveDescription_Substitute[] =  _("Crée un leurre\navec 1/4 des PV\nmax du lanceur.");
const u8 gMoveDescription_Struggle[] =  _("Fonctionne s'il ne\nreste plus de PP.\nBlesse légèrement\nle lanceur.");
const u8 gMoveDescription_Sketch[] =  _("Copie en\npermanence la\ndernière attaque\nennemie.");
const u8 gMoveDescription_TripleKick[] =  _("Trois coups de pied\nde plus en plus\npuissants.");
const u8 gMoveDescription_Thief[] =  _("Peut voler l'objet\ntenu par l'ennemi\npendant l'attaque.");
const u8 gMoveDescription_SpiderWeb[] =  _("Capture l'ennemi\net empêche\ntoute fuite ou\nchangement.");
const u8 gMoveDescription_MindReader[] =  _("Pressent l'action\npour réussir\nl'attaque suivante.");
const u8 gMoveDescription_Nightmare[] =  _("Un cauchemar qui\ninflige des dégâts\nà chaque tour à\nl'ennemi endormi.");
const u8 gMoveDescription_FlameWheel[] =  _("Une charge\nenflammée qui\npeut brûler\nl'ennemi.");
const u8 gMoveDescription_Snore[] =  _("Attaque sonore qui\nne peut être lancée\nqu'endormi.");
const u8 gMoveDescription_Curse[] =  _("Coup qui fonctionne\nautrement pour les\nSPECTRES.");
const u8 gMoveDescription_Flail[] =  _("Inflige plus de\ndégâts quand le\nlanceur n'a presque\nplus de PV.");
const u8 gMoveDescription_Conversion2[] =  _("Permet de résister\nau type de la\ndernière attaque.");
const u8 gMoveDescription_Aeroblast[] =  _("Implosion à taux de\ncritiques élevé.");
const u8 gMoveDescription_CottonSpore[] =  _("Envoie des spores\npour baisser\nbeaucoup la\nVITESSE.");
const u8 gMoveDescription_Reversal[] =  _("Inflige plus de\ndégâts quand les\nPV du lanceur\nsont faibles.");
const u8 gMoveDescription_Spite[] =  _("Réduit de 2 à 5 \nles PP de la\ndernière attaque\nennemie.");
const u8 gMoveDescription_PowderSnow[] =  _("Envoie une rafale\nde neige. Peut\ngeler l'ennemi.");
const u8 gMoveDescription_Protect[] =  _("Esquive l'attaque,\nmais peut échouer\nsi réutilisé.");
const u8 gMoveDescription_MachPunch[] =  _("Coup de poing\nfulgurant. Permet\nde frapper en 1{SUPER_ER}.");
const u8 gMoveDescription_ScaryFace[] =  _("Effraye avec une\ngrimace pour\nbaisser beaucoup\nla VITESSE.");
const u8 gMoveDescription_FaintAttack[] =  _("Attire l'ennemi et\nfrappe sans jamais\néchouer.");
const u8 gMoveDescription_SweetKiss[] =  _("Demande un bisou\ntout mignon. Peut\nrendre confus.");
const u8 gMoveDescription_BellyDrum[] =  _("Améliore l'ATTAQUE\nà fond en sacrifiant\nla moitié des PV.");
const u8 gMoveDescription_SludgeBomb[] =  _("Envoie des détritus\npour blesser.\nPeut empoisonner.");
const u8 gMoveDescription_MudSlap[] =  _("Envoie de la boue\nau visage pour\nbaisser la\nprécision.");
const u8 gMoveDescription_Octazooka[] =  _("Jette de l'encre au\nvisage de l'ennemi\npour baisser sa\nprécision.");
const u8 gMoveDescription_Spikes[] =  _("Pointes pour\npiéger les ennemis\nqui échangent leur\nplace.");
const u8 gMoveDescription_ZapCannon[] =  _("Puissant et\nparalysant, mais\npas très précis.");
const u8 gMoveDescription_Foresight[] =  _("Empêche l'ennemi\nd'améliorer son\nesquive.");
const u8 gMoveDescription_DestinyBond[] =  _("Si le lanceur est\nmis KO, l'ennemi\nle sera également.");
const u8 gMoveDescription_PerishSong[] =  _("Un POKéMON qui\nentend ce requiem\nest KO en 3 tours.");
const u8 gMoveDescription_IcyWind[] =  _("Attaque glaciale.\nBaisse la VITESSE\nde l'ennemi.");
const u8 gMoveDescription_Detect[] =  _("Esquive l'attaque,\nmais peut échouer\nsi réutilisé.");
const u8 gMoveDescription_BoneRush[] =  _("Frappe l'ennemi\n2 à 5 fois\navec un os.");
const u8 gMoveDescription_LockOn[] =  _("Verrouille la cible\npour ne pas la\nrater au tour\nsuivant.");
const u8 gMoveDescription_Outrage[] =  _("Une attaque\nfurieuse sur\n2 à 3 tours.\nLanceur confus.");
const u8 gMoveDescription_Sandstorm[] =  _("Une tempête de\nsable qui souffle\npendant 5 tours.");
const u8 gMoveDescription_GigaDrain[] =  _("Absorbe la moitié\ndes dégâts infligés\net les convertit en\nPV.");
const u8 gMoveDescription_Endure[] =  _("Résiste aux\nattaques du tour\navec 1 PV. Peut\néchouer si répété.");
const u8 gMoveDescription_Charm[] =  _("Charme l'ennemi\net baisse\nbeaucoup son\nATTAQUE.");
const u8 gMoveDescription_Rollout[] =  _("Une attaque sur\n5 tours, de plus en\nplus puissante.");
const u8 gMoveDescription_FalseSwipe[] =  _("Une attaque qui\nlaisse au\nmoins 1 PV à\nl'ennemi.");
const u8 gMoveDescription_Swagger[] =  _("Rend l'ennemi\nconfus et\nbooste l'ATTAQUE.");
const u8 gMoveDescription_MilkDrink[] =  _("Regagne jusqu'à\nla moitié des PV\nmax du lanceur\nou d'un allié.");
const u8 gMoveDescription_Spark[] =  _("Une charge\nélectrique qui peut\nparalyser l'ennemi.");
const u8 gMoveDescription_FuryCutter[] =  _("Une attaque qui\ns'intensifie après\nchaque coup.");
const u8 gMoveDescription_SteelWing[] =  _("Frappe l'ennemi en \ndéployant ses ailes\nd'acier. Peut\nmonter la DEFENSE.");
const u8 gMoveDescription_MeanLook[] =  _("Lance un regard\nméchant pour\nempêcher la fuite.");
const u8 gMoveDescription_Attract[] =  _("Le genre opposé\na moins de\nchances d'attaquer.");
const u8 gMoveDescription_SleepTalk[] =  _("Utilise un coup\nau hasard\nen dormant.");
const u8 gMoveDescription_HealBell[] =  _("Carillon apaisant\nqui soigne les \nchangements de\nstatut des alliés.");
const u8 gMoveDescription_Return[] =  _("Attaque dont la\npuissance dépend\nde l'amitié avec le\nDRESSEUR.");
const u8 gMoveDescription_Present[] =  _("Cadeau en forme\nde bombe. Peut\nrestaurer des PV.");
const u8 gMoveDescription_Frustration[] =  _("Attaque plus\npuissante si le\nDRESSEUR est\nmal aimé.");
const u8 gMoveDescription_Safeguard[] =  _("Force mystique\nempêchant tout\nchangement de\nstatut.");
const u8 gMoveDescription_PainSplit[] =  _("Ajoute les PV des\ndeux combattants\net les partage.");
const u8 gMoveDescription_SacredFire[] =  _("Une attaque de feu\npuissante et\nmystique\npouvant brûler.");
const u8 gMoveDescription_Magnitude[] =  _("Un tremblement\nde terre d'intensité\nvariable.");
const u8 gMoveDescription_DynamicPunch[] =  _("Puissant et rend\nconfus,  mais pas\ntrès précis.");
const u8 gMoveDescription_Megahorn[] =  _("Une charge\nviolente, toutes\ncornes en avant.");
const u8 gMoveDescription_DragonBreath[] =  _("Frappe l'ennemi\ngrâce à un souffle\nsuper puissant\npouvant paralyser.");
const u8 gMoveDescription_BatonPass[] =  _("Change de lanceur,\nmais transmet les\nchangements de\nstats.");
const u8 gMoveDescription_Encore[] =  _("Oblige l'ennemi à\nrépéter sa dernière\naction 2 à 6 tours.");
const u8 gMoveDescription_Pursuit[] =  _("Inflige de sérieux\ndégâts lorsque\nl'ennemi change.");
const u8 gMoveDescription_RapidSpin[] =  _("Frappe l'ennemi\nen tournant sur\nsoi-même.");
const u8 gMoveDescription_SweetScent[] =  _("Séduit l'ennemi\npour baisser son\nesquive. Attire les\nPOKéMON sauvages.");
const u8 gMoveDescription_IronTail[] =  _("Attaque avec la\nqueue. Peut baisser\nla DEFENSE.");
const u8 gMoveDescription_MetalClaw[] =  _("Attaque avec des\ngriffes. Peut\naugmenter\nl'ATTAQUE.");
const u8 gMoveDescription_VitalThrow[] =  _("Attaque après\nl'ennemi, mais\nn'échoue jamais.");
const u8 gMoveDescription_MorningSun[] =  _("Restaure les PV.\nLa quantité varie\nsuivant le temps.");
const u8 gMoveDescription_Synthesis[] =  _("Restaure les PV.\nLa quantité varie\nsuivant le temps.");
const u8 gMoveDescription_Moonlight[] =  _("Restaure les PV.\nLa quantité varie\nsuivant le temps.");
const u8 gMoveDescription_HiddenPower[] =  _("L'efficacité et le\ntype de l'attaque\ndépendent du\nlanceur.");
const u8 gMoveDescription_CrossChop[] =  _("2 attaques\ntranchantes. Taux\nde critiques élevé.");
const u8 gMoveDescription_Twister[] =  _("Déclenche un\nterrible ouragan\nblessant l'ennemi.\nPeut apeurer.");
const u8 gMoveDescription_RainDance[] =  _("Améliore les\nattaques EAU\npendant 5 tours.");
const u8 gMoveDescription_SunnyDay[] =  _("Améliore les\nattaques FEU\npendant 5 tours.");
const u8 gMoveDescription_Crunch[] =  _("Utilise ses crocs\npointus. Peut\nbaisser la\nDEF. SPE.");
const u8 gMoveDescription_MirrorCoat[] =  _("Renvoie l'attaque\nspéciale ennemie\n2 fois plus fort.");
const u8 gMoveDescription_PsychUp[] =  _("Copie les effets\nde l'ennemi et les\npasse au lanceur.");
const u8 gMoveDescription_ExtremeSpeed[] =  _("Une attaque\nextrêmement\nrapide et\npuissante.");
const u8 gMoveDescription_AncientPower[] =  _("Une attaque\npouvant augmenter\ntoutes les stats.");
const u8 gMoveDescription_ShadowBall[] =  _("Projette une\ngrande tache\nqui peut baisser\nla DEF. SPE.");
const u8 gMoveDescription_FutureSight[] =  _("Accumule de\nl'énergie pour\nfrapper 2 tours\nplus tard.");
const u8 gMoveDescription_RockSmash[] =  _("Une attaque qui\npeut baisser la\nDEFENSE et briser\ndes rochers.");
const u8 gMoveDescription_Whirlpool[] =  _("Piège l'ennemi\ndans un tourbillon\npendant\n2 à 5 tours.");
const u8 gMoveDescription_BeatUp[] =  _("Appelle les\nPOKéMON de l'équipe\nà se joindre à\nl'attaque.");
const u8 gMoveDescription_FakeOut[] =  _("Une attaque en\ndébut de bataille\npour apeurer.");
const u8 gMoveDescription_Uproar[] =  _("Brouhaha de\n2 à 5 tours.\nEmpêche de\ndormir.");
const u8 gMoveDescription_Stockpile[] =  _("Accumule de la\npuissance pendant\n3 tours maximum.");
const u8 gMoveDescription_SpitUp[] =  _("Libère la puissance\nprécédemment\naccumulée avec\nSTOCKAGE.");
const u8 gMoveDescription_Swallow[] =  _("Absorbe la\npuissance accumulée\navec STOCKAGE\net restaure les PV.");
const u8 gMoveDescription_HeatWave[] =  _("Un souffle ardent\npouvant brûler\nl'ennemi.");
const u8 gMoveDescription_Hail[] =  _("Tempête de grêle\nqui dure\npendant 5 tours.");
const u8 gMoveDescription_Torment[] =  _("Perturbe l'ennemi.\nEmpêche la\nréutilisation d'une\nattaque.");
const u8 gMoveDescription_Flatter[] =  _("Rend l'ennemi\nconfus, mais\naugmente son \nATQ. SPE.");
const u8 gMoveDescription_WillOWisp[] =  _("Inflige une\ndouloureuse \nbrûlure à l'ennemi.");
const u8 gMoveDescription_Memento[] =  _("Le lanceur est mis\nKO mais baisse\nbeaucoup l'ATTAQUE\net l'ATQ. SPE.");
const u8 gMoveDescription_Facade[] =  _("Booste l'ATTAQUE\nsi le lanceur est\nbrûlé, paralysé\nou empoisonné.");
const u8 gMoveDescription_FocusPunch[] =  _("Attaque en dernier.\nLanceur apeuré\nsi touché avant.");
const u8 gMoveDescription_SmellingSalt[] =  _("Doublement efficace\ncontre les ennemis\nparalysés, mais\nles soigne.");
const u8 gMoveDescription_FollowMe[] =  _("Attire l'attention.\nLes adversaires.\nn'attaquent que le\nlanceur.");
const u8 gMoveDescription_NaturePower[] =  _("Le type de\nl'attaque change\nselon le lieu\ndu combat.");
const u8 gMoveDescription_Charge[] =  _("Charge de la\npuissance pour son\nattaque ELECTRIK\nsuivante.");
const u8 gMoveDescription_Taunt[] =  _("Provoque l'ennemi.\nL'oblige à utiliser\nseulement ses\nattaques.");
const u8 gMoveDescription_HelpingHand[] =  _("Améliore la\npuissance\nd'attaque du\nreceveur.");
const u8 gMoveDescription_Trick[] =  _("Oblige la cible à\néchanger\nles objets tenus.");
const u8 gMoveDescription_RolePlay[] =  _("Imite la cible et\ncopie sa capacité\nspéciale.");
const u8 gMoveDescription_Wish[] =  _("Un vœu qui\nrestaure la moitié \ndes PV au tour\nsuivant.");
const u8 gMoveDescription_Assist[] =  _("Attaque au hasard\navec un coup d'un\ndes partenaires.");
const u8 gMoveDescription_Ingrain[] =  _("Plante des racines\npour gagner des PV\nchaque tour. Ne\npeut plus changer.");
const u8 gMoveDescription_Superpower[] =  _("Attaque puissante\nmais baisse les\nstats d'ATTAQUE\net DEFENSE.");
const u8 gMoveDescription_MagicCoat[] =  _("Renvoie au lanceur\nVAMPIGRAINE et les\ncapacités qui\nchangent le statut.");
const u8 gMoveDescription_Recycle[] =  _("Recycle un objet\npour l'utiliser une\nfois de plus.");
const u8 gMoveDescription_Revenge[] =  _("Gagne en puissance\nquand blessé par\nl'ennemi.");
const u8 gMoveDescription_BrickBreak[] =  _("Attaque qui brise\nles barrières comme\nPROTECTION et\nMUR LUMIERE.");
const u8 gMoveDescription_Yawn[] =  _("Fait bâiller\nl'ennemi qui\ns'endort au tour\nsuivant.");
const u8 gMoveDescription_KnockOff[] =  _("Frappe l'objet\ntenu par l'ennemi\npour le rendre\ninutilisable.");
const u8 gMoveDescription_Endeavor[] =  _("Gagne en\npuissance si PV\ninférieurs aux\nPV ennemis.");
const u8 gMoveDescription_Eruption[] =  _("Inflige plus de\ndégâts si les PV\ndu lanceur sont\nélevés.");
const u8 gMoveDescription_SkillSwap[] =  _("Le lanceur et la\ncible échangent\nleur capacité\nspéciale.");
const u8 gMoveDescription_Imprison[] =  _("Empêche les\nennemis d'utiliser\nles coups connus\ndu lanceur.");
const u8 gMoveDescription_Refresh[] =  _("Soigne un\nempoisonnement,\nune paralysie ou\nune brûlure.");
const u8 gMoveDescription_Grudge[] =  _("Si mis KO,\nsupprime les PP\ndu coup ennemi.");
const u8 gMoveDescription_Snatch[] =  _("Vole les effets de\nchang. de statut\nde la prochaine\nattaque ennemie.");
const u8 gMoveDescription_SecretPower[] =  _("Les effets de\nl'attaque\ndépendent du lieu.");
const u8 gMoveDescription_Dive[] =  _("Plonge en apnée\nau premier tour et\nfrappe au second.");
const u8 gMoveDescription_ArmThrust[] =  _("Coups de poing\narrêtés qui\nfrappent 2 à\n5 fois.");
const u8 gMoveDescription_Camouflage[] =  _("Change le type\ndu POKéMON\nselon le lieu.");
const u8 gMoveDescription_TailGlow[] =  _("Flash lumineux\nqui booste\nl'ATQ. SPE.");
const u8 gMoveDescription_LusterPurge[] =  _("Envoie une lueur\nintense. Peut\naussi baisser la \nDEF. SPE.");
const u8 gMoveDescription_MistBall[] =  _("Envoie une rafale\nde duvet. Peut \naussi baisser\nl'ATQ. SPE.");
const u8 gMoveDescription_FeatherDance[] =  _("Enveloppe\nl'ennemi de duvet\net baisse beaucoup\nl'ATTAQUE.");
const u8 gMoveDescription_TeeterDance[] =  _("Danse qui rend\nconfus tous les\ncombattants.");
const u8 gMoveDescription_BlazeKick[] =  _("Coup de pied à\ntaux de critiques\nélevé. Peut brûler.");
const u8 gMoveDescription_MudSport[] =  _("Couvre le lanceur\nde boue pour\nrésister aux\nattaques ELECTRIK.");
const u8 gMoveDescription_IceBall[] =  _("Une attaque en\n5 tours de\nplus en plus\npuissante.");
const u8 gMoveDescription_NeedleArm[] =  _("Attaque avec\ndes bras épineux.\nPeut apeurer.");
const u8 gMoveDescription_SlackOff[] =  _("Se détend et\nrécupère la moitié\ndes PV maximum.");
const u8 gMoveDescription_HyperVoice[] =  _("Attaque bruyante\nblessant avec des\nondes sonores.");
const u8 gMoveDescription_PoisonFang[] =  _("Morsure pouvant\nsérieusement\nempoisonner\nl'ennemi.");
const u8 gMoveDescription_CrushClaw[] =  _("Lacère avec\ndes griffes. Peut\nbaisser la\nDEFENSE.");
const u8 gMoveDescription_BlastBurn[] =  _("Puissant, mais\nimmobilise le\nlanceur le tour\nsuivant.");
const u8 gMoveDescription_HydroCannon[] =  _("Puissant, mais\nimmobilise le\nlanceur le tour\nsuivant.");
const u8 gMoveDescription_MeteorMash[] =  _("Coup de poing\nmétéore. Peut\naugmenter\nl'ATTAQUE.");
const u8 gMoveDescription_Astonish[] =  _("Une attaque qui\npeut choquer et\napeurer l'ennemi.");
const u8 gMoveDescription_WeatherBall[] =  _("Le type et la\npuissance de\nl'attaque varient\nselon le climat.");
const u8 gMoveDescription_Aromatherapy[] =  _("Parfum apaisant\nsoignant les\nchangements de\nstatut.");
const u8 gMoveDescription_FakeTears[] =  _("Fait semblant de\npleurer pour\nbaisser beaucoup\nla DEF. SPE.");
const u8 gMoveDescription_AirCutter[] =  _("Déclenche un vent\ntranchant. Taux de\ncritiques élevé.");
const u8 gMoveDescription_Overheat[] =  _("Attaque à pleine\npuissance, mais\nbaisse beaucoup\nl'ATQ. SPE.");
const u8 gMoveDescription_OdorSleuth[] =  _("Empêche l'ennemi\nd'augmenter son\nesquive.");
const u8 gMoveDescription_RockTomb[] =  _("Immobilise l'ennemi\navec des rochers.\nBaisse la VITESSE.");
const u8 gMoveDescription_SilverWind[] =  _("Attaque poudreuse\nqui peut augmenter\nles capacités du\nlanceur.");
const u8 gMoveDescription_MetalSound[] =  _("Cri horrible qui\nbaisse beaucoup\nla DEF. SPE.");
const u8 gMoveDescription_GrassWhistle[] =  _("Endort l'ennemi\nen sifflant une\ndouce mélodie.");
const u8 gMoveDescription_Tickle[] =  _("Fait rire l'ennemi\net baisse\nson ATTAQUE et\nsa DEFENSE.");
const u8 gMoveDescription_CosmicPower[] =  _("Le lanceur absorbe\nun pouvoir qui\nmonte la DEFENSE\net la DEF. SPE.");
const u8 gMoveDescription_WaterSpout[] =  _("Inflige plus de\ndégâts si le\nlanceur a\nbeaucoup de PV.");
const u8 gMoveDescription_SignalBeam[] =  _("Un étrange rayon\nqui peut rendre\nl'ennemi confus.");
const u8 gMoveDescription_ShadowPunch[] =  _("Un coup de poing\nimparable\nsortant de l'ombre.");
const u8 gMoveDescription_Extrasensory[] =  _("Pouvoir singulier\nqui peut\napeurer l'ennemi.");
const u8 gMoveDescription_SkyUppercut[] =  _("Un uppercut porté\nen direction du\nciel.");
const u8 gMoveDescription_SandTomb[] =  _("Piège l'ennemi dans\nun cyclone de\n2 à 5 tours.");
const u8 gMoveDescription_SheerCold[] =  _("Attaque glacée qui\nmet KO quand elle\nest réussie.");
const u8 gMoveDescription_MuddyWater[] =  _("Attaque d'eau\ncroupie. Peut\nbaisser la\nprécision.");
const u8 gMoveDescription_BulletSeed[] =  _("Mitraille l'ennemi\navec 2 à 5 rafales\nde graines à\nla suite.");
const u8 gMoveDescription_AerialAce[] =  _("Attaque très\nrapide et\nimparable.");
const u8 gMoveDescription_IcicleSpear[] =  _("Mitraille l'ennemi\navec 2 à 5 glaçons\nà la suite.");
const u8 gMoveDescription_IronDefense[] =  _("Endurcit le corps\npour booster la\nDEFENSE.");
const u8 gMoveDescription_Block[] =  _("Bloque la route\nde l'ennemi\npour empêcher\nsa fuite.");
const u8 gMoveDescription_Howl[] =  _("Grogne pour se\nrassurer et booster\nl'ATTAQUE.");
const u8 gMoveDescription_DragonClaw[] =  _("Tranche violemment\nl'ennemi avec des\ngriffes acérées.");
const u8 gMoveDescription_FrenzyPlant[] =  _("Puissant, mais\nimmobilise le\nlanceur le tour\nsuivant.");
const u8 gMoveDescription_BulkUp[] =  _("Se gonfle pour\nbooster l'ATTAQUE\net la DEFENSE.");
const u8 gMoveDescription_Bounce[] =  _("Saute et tombe\nle tour suivant.\nPeut paralyser.");
const u8 gMoveDescription_MudShot[] =  _("Envoie de la boue\nà l'ennemi\npour réduire sa\nVITESSE.");
const u8 gMoveDescription_PoisonTail[] =  _("Attaque à taux de\ncritiques élevé.\nPeut aussi\nempoisonner.");
const u8 gMoveDescription_Covet[] =  _("Demande gentiment\nun objet détenu\npar l'ennemi.");
const u8 gMoveDescription_VoltTackle[] =  _("Une dangereuse\ncharge électrique\nqui blesse aussi le\nlanceur.");
const u8 gMoveDescription_MagicalLeaf[] =  _("Une attaque qui\nutilise une feuille\nétrange. Elle est\nimparable.");
const u8 gMoveDescription_WaterSport[] =  _("Mouille le lanceur\net augmente sa\nrésistance au feu.");
const u8 gMoveDescription_CalmMind[] =  _("Méditation pour\naugmenter\nl'ATQ. SPE. et la\nDEF. SPE.");
const u8 gMoveDescription_LeafBlade[] =  _("Tranche avec une\nfeuille. Taux de\ncritiques élevé.");
const u8 gMoveDescription_DragonDance[] =  _("Danse mystique\naugmentant\nl'ATTAQUE et\nla VITESSE.");
const u8 gMoveDescription_RockBlast[] =  _("Projette des\nrochers sur\nl'ennemi 2 à 5 fois\nde suite.");
const u8 gMoveDescription_ShockWave[] =  _("Attaque électrique\nrapide et\nimpossible à\nesquiver.");
const u8 gMoveDescription_WaterPulse[] =  _("Envoi des ondes\naquatiques.\nPeut rendre confus.");
const u8 gMoveDescription_DoomDesire[] =  _("Charge la\nlumière pour\nfrapper 2 tours\nplus tard.");
const u8 gMoveDescription_PsychoBoost[] =  _("Attaque à pleine\npuissance, mais\nbaisse beaucoup\nl'ATQ. SPE.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
